form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          mssqlserverInstanceDown:
            duration: 0m
            enabled: true
            severity: critical
          mssqlserverRestarted:
            duration: 0m
            enabled: true
            severity: critical
            val: 60
          mssqlserverServiceDown:
            duration: 0m
            enabled: true
            severity: critical
      kubeStash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: mssqlservers
    kind: MSSQLServer
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComMSSQLServerAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: MSSQLServerAutoscaler
    metadata:
      name: sqlserver-ag
      namespace: demo
  catalogAppscodeComMSSQLServerBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: MSSQLServerBinding
    metadata:
      name: sqlserver-ag
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: sqlserver-ag-ca
      namespace: sample
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: sqlserver-ag
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: sqlserver-ag
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: sqlserver-ag
      namespace: demo
  gitopsKubedbComMSSQLServer: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: MSSQLServer
    metadata:
      name: sqlserver-ag
      namespace: sample
  kubedbComMSSQLServer: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: MSSQLServer
    metadata:
      name: sqlserver-ag
      namespace: sample
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: sqlserver-ag
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: sqlserver-ag-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: sqlserver-ag-config
      namespace: demo
