chart:
  name: autoscalingkubedbcom-oracleautoscaler-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a OracleAutoscaler Editor
  description: OracleAutoscaler Editor
  name: OracleAutoscaler Editor by AppsCode
  shortName: OracleAutoscaler Editor
  url: https://appscode.com
release:
  name: autoscalingkubedbcom-oracleautoscaler-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
