chart:
  name: kubedbcom-milvus-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a Milvus Editor
  description: Milvus Editor
  name: Milvus Editor by AppsCode
  shortName: Milvus Editor
  url: https://appscode.com
release:
  name: kubedbcom-milvus-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
