form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          milvusGoroutinesExplosion:
            duration: 1m
            enabled: true
            severity: warning
            val: 1000
          milvusHighCPUUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          milvusHighFDsUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 110
          milvusHighMemoryUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          milvusHighProcessMemoryUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 8e+08
          milvusHighThreadPressure:
            duration: 1m
            enabled: true
            severity: warning
            val: 60
          milvusInstanceDown:
            duration: 30s
            enabled: true
            severity: critical
          milvusRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: prometheus
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: milvuses
    kind: Milvus
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComMilvusAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: MilvusAutoscaler
    metadata:
      name: milvus
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: milvus-ca
      namespace: demo
  kubedbComMilvus: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Milvus
    metadata:
      name: milvus
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: milvus
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: milvus-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: milvus-config
      namespace: demo
