chart:
  name: monitoringk8sappscodecom-telemetrystack-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a TelemetryStack Editor
  description: TelemetryStack Editor
  name: TelemetryStack Editor by AppsCode
  shortName: TelemetryStack Editor
  url: https://appscode.com
release:
  name: monitoringk8sappscodecom-telemetrystack-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
