chart:
  name: uikubedbcom-databaseconfiguration-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DatabaseConfiguration Editor
  description: DatabaseConfiguration Editor
  name: DatabaseConfiguration Editor by AppsCode
  shortName: DatabaseConfiguration Editor
  url: https://appscode.com
release:
  name: uikubedbcom-databaseconfiguration-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
