- elements:
  - label: To update Exporter Resource section click on Create OpsRequest
    type: label-element
  - init:
      type: func
      value: getOpsRequestUrl|scale-vertically
    label: Create OpsRequest
    schema: temp/properties/opsRequestUrl
    type: anchor
  - fullwidth: true
    init:
      type: func
      value: isValueExistInModel|/resources/kubedbComHanaDB/spec/monitor
    label: Enable Monitoring
    schema: temp/properties/enableMonitoring
    type: switch
    watcher:
      func: onEnableMonitoringChange
      paths:
      - temp/properties/enableMonitoring
  - elements:
    - init:
        type: static
        value: prometheus.io/operator
      isHorizontal: true
      label: Select a Monitoring Method
      options:
      - description: Inject metric exporter sidecar and creates a ServiceMonitor
        text: Prometheus Operator
        value: prometheus.io/operator
      - description: Injects the metric exporter sidecar and let you customize ServiceMonitor
        text: Custom ServiceMonitor
        value: prometheus.io
      - description: Inject metric exporter sidecar and add Prometheus annotations
          to the stats Service
        text: Custom Scrapper
        value: prometheus.io/builtin
      schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/agent
      type: radio
      watcher:
        func: onAgentChange
        paths:
        - schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/agent
    - elements:
      - label: Scrapping Interval
        schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/prometheus/properties/serviceMonitor/properties/interval
        type: input
      if:
        name: isEqualToModelPathValue|prometheus.io/operator|/resources/kubedbComHanaDB/spec/monitor/agent
        type: function
      label: ServiceMonitor Configuration
      showLabels: true
      type: block-layout
    - elements:
      - buttonClass: is-light is-outlined
        elements:
        - fullwidth: true
          label: Honor labels
          schema: honorLabels
          type: switch
        - label: Interval
          schema: interval
          type: input
          validation:
            type: required
        - label: Path
          schema: path
          type: input
          validation:
            type: required
        - label: Port
          schema: port
          type: input
          validation:
            type: required
        label: Endpoints
        schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/spec/properties/endpoints
        type: array-object-form
      - if:
          name: returnFalse
          type: function
        label: Match Namespaces
        loader: getResources|core|v1|namespaces
        multiple: true
        schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/spec/properties/namespaceSelector/properties/matchNames
        type: select
      - elements:
        - label: Labels
          schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/spec/properties/selector/properties/matchLabels
          type: object-item
        if:
          name: returnFalse
          type: function
        showLabels: false
        type: block-layout
      if:
        name: isEqualToModelPathValue|prometheus.io|/resources/kubedbComHanaDB/spec/monitor/agent
        type: function
      label: Service Monitor
      showLabels: true
      type: block-layout
    - buttonClass: is-light is-outlined
      if:
        name: isEqualToModelPathValue|prometheus.io|/resources/kubedbComHanaDB/spec/monitor/agent
        type: function
      label: Labels
      schema: schema/properties/resources/properties/monitoringCoreosComServiceMonitor/properties/metadata/properties/labels
      type: object-item
    - label: Exporter Configuration
      schema: ""
      type: label-element
    - fullwidth: true
      init:
        type: static
        value: true
      label: Customize Exporter Sidecar
      schema: temp/properties/customizeExporter
      type: switch
      watcher:
        func: onCustomizeExporterChange
        paths:
        - temp/properties/customizeExporter
    - elements:
      - if:
          name: returnFalse
          type: function
        label: Resources
        schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/resources
        type: machine-compare
      - label: Security Context
        schema: ""
        type: label-element
      - label: Run as User
        schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/securityContext/properties/runAsUser
        type: input
      - label: Run as Group
        schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/securityContext/properties/runAsGroup
        type: input
      - label: Port
        schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/port
        type: input
      - buttonClass: is-light is-outlined
        element:
          label: Args
          type: input
        init:
          type: static
          value:
          - --compatible-mode
        label: Args
        schema: schema/properties/resources/properties/kubedbComHanaDB/properties/spec/properties/monitor/properties/prometheus/properties/exporter/properties/args
        type: array-item-form
      - elements:
        - buttonClass: is-light is-outlined
          elements:
          - label: Name
            schema: name
            type: input
            validation:
              type: required
          - init:
              type: func
              value: setValueFrom
            label: Value From
            options:
            - text: Input
              value: input
            - text: Secret
              value: secret
            - text: ConfigMap
              value: configMap
            schema: temp/properties/valueFromType
            type: radio
            validation:
              type: required
            watcher:
              func: onValueFromChange
              paths:
              - temp/properties/valueFromType
          - if:
              name: isEqualToTemp|input
              type: function
            label: Value
            schema: value
            type: input
            validation:
              type: required
          - if:
              name: isEqualToTemp|configMap
              type: function
            label: ConfigMap Name
            loader:
              name: resourceNames|core|v1|configmaps
              watchPaths:
              - schema/metadata/release/namespace
            schema: valueFrom/properties/configMapKeyRef/properties/name
            type: select
            validation:
              type: required
          - if:
              name: isEqualToTemp|configMap
              type: function
            label: ConfigMap Key
            loader:
              name: getConfigMapKeys
              watchPaths:
              - schema/resources/kubedbComHanaDB/spec/monitor/prometheus/exporter/env/dynamicIndex/valueFrom/configMapKeyRef/name
              - schema/metadata/release/namespace
            schema: valueFrom/properties/configMapKeyRef/properties/key
            type: select
          - if:
              name: isEqualToTemp|secret
              type: function
            label: Secret Name
            loader:
              name: getSecrets
              watchPaths:
              - schema/metadata/release/namespace
            schema: valueFrom/properties/secretKeyRef/properties/name
            type: select
            validation:
              type: required
          - if:
              name: isEqualToTemp|secret
              type: function
            label: Secret Key
            loader:
              name: getSecretKeys
              watchPaths:
              - schema/resources/kubedbComHanaDB/spec/monitor/prometheus/exporter/env/dynamicIndex/valueFrom/secretKeyRef/name
              - schema/metadata/release/namespace
            schema: valueFrom/properties/secretKeyRef/properties/key
            type: select
          init:
            type: func
            value: initEnvArray
          label: Environment Variables
          schema: temp/properties/env
          type: array-object-form
          watcher:
            func: onEnvArrayChange
            paths:
            - temp/properties/env
        label: Metadata
        showLabels: false
        type: block-layout
      if:
        name: showCustomizeExporterSection
        type: function
      label: Customer Exporter Section
      showLabels: false
      type: block-layout
    if:
      name: showMonitoringSection
      type: function
    type: block-layout
  id: monitoring
  loader: initMonitoring
  type: single-step-form
type: multi-step-form
