en:
  labels:
    agent: Select a Monitoring Method
    hanadb: HanaDB
    customize_exporter: Customize Exporter Sidecar
    enable_monitoring: Enable Monitoring
    exporter_configuration: Exporter Configuration
    honor_labels: Honor labels
    interval: Interval
    path: Path
    port: Port
    run_as_group: Run as Group
    run_as_user: Run as User
    scrapping_interval: Scrapping Interval
    service_monitor: Service Monitor
    service_monitor_configuration: ServiceMonitor Configuration
  options:
    agent:
      prometheus:
        description: Injects the metric exporter sidecar and let you customize ServiceMonitor
        label: Custom ServiceMonitor
      prometheus_builtin:
        description: Inject metric exporter sidecar and add Prometheus annotations to the stats Service
        label: Custom Scrapper
      prometheus_operator:
        description: Inject metric exporter sidecar and creates a ServiceMonitor
        label: Prometheus Operator
