metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_csi_driver_nfs: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: csi-driver-nfs
      name: csi-driver-nfs
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_longhorn: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: longhorn
      name: longhorn
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_snapshot_controller: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: snapshot-controller
      name: snapshot-controller
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_topolvm: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: topolvm
      name: topolvm
      namespace: kubeops
