metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_cluster_manager_spoke: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-manager-spoke
      name: cluster-manager-spoke
      namespace: kubeops
