metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_gatekeeper: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: gatekeeper
      name: gatekeeper
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_gatekeeper_constraints: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: gatekeeper-constraints
      name: gatekeeper-constraints
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_gatekeeper_grafana_dashboards: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: gatekeeper-grafana-dashboards
      name: gatekeeper-grafana-dashboards
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_gatekeeper_templates: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: gatekeeper-templates
      name: gatekeeper-templates
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kyverno: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kyverno
      name: kyverno
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kyverno_policies: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kyverno-policies
      name: kyverno-policies
      namespace: kubeops
