chart:
  name: opskubedbcom-qdrantopsrequest-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a QdrantOpsRequest Editor
  description: QdrantOpsRequest Editor
  name: QdrantOpsRequest Editor by AppsCode
  shortName: QdrantOpsRequest Editor
  url: https://appscode.com
release:
  name: opskubedbcom-qdrantopsrequest-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
