chart:
  name: opskubedbcom-aerospikeopsrequest-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a AerospikeOpsRequest Editor
  description: AerospikeOpsRequest Editor
  name: AerospikeOpsRequest Editor by AppsCode
  shortName: AerospikeOpsRequest Editor
  url: https://appscode.com
release:
  name: opskubedbcom-aerospikeopsrequest-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
