step:
- loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
  id: opscenter-cost
  elements:
  - type: checkbox
    schema: temp/properties/enabledFeatures
    label: ''
    loader: fetchFeatureSetOptions
    init:
      type: func
      value: getEnabledFeatures
    watcher:
      func: onEnabledFeaturesChange
      paths:
        - temp/properties/enabledFeatures
  - type: info
    customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    watcher:
      func: checkIsResourceLoaded
      paths:
        - temp/properties/isResourceLoaded  
type: multi-step-form
