metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: documentdbs
    kind: DocumentDB
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComDocumentDBAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: DocumentDBAutoscaler
    metadata:
      name: documentdb
      namespace: demo
  kubedbComDocumentDB: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: DocumentDB
    metadata:
      name: documentdb
      namespace: default
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: documentdb-auth
      namespace: demo
