metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: documentdbs
    kind: DocumentDB
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComDocumentDBAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: DocumentDBAutoscaler
    metadata:
      name: documentdb
      namespace: demo
    spec:
      compute:
        documentdb:
          maxAllowed:
            cpu: 1
            memory: 2Gi
          minAllowed:
            cpu: 400m
            memory: 400Mi
          podLifeTimeThreshold: 10m
          resourceDiffPercentage: 20
          trigger: "On"
        nodeTopology:
          name: standard-basv2-family
      databaseRef:
        name: documentdb
      opsRequestOptions:
        apply: IfReady
        timeout: 10m
  kubedbComDocumentDB: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: DocumentDB
    metadata:
      name: documentdb
      namespace: default
    spec:
      deletionPolicy: WipeOut
      podTemplate:
        spec:
          containers:
            - name: documentdb
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
          nodeSelector:
            app: documentdbs.kubedb.com
            instance: hello
            namespace: default
            nodepool: standard-bsv2-family
          podPlacementPolicy:
            name: default
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: documentdbs.kubedb.com
            - effect: NoSchedule
              key: instance
              operator: Equal
              value: hello
            - effect: NoSchedule
              key: namespace
              operator: Equal
              value: default
            - effect: NoSchedule
              key: nodepool
              operator: Equal
              value: standard-bsv2-family
      replicas: 3
      serviceTemplates:
        - alias: primary
          spec:
            type: LoadBalancer
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: default
      storageType: Durable
      version: 24.4.1
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: documentdb-auth
      namespace: demo
    stringData:
      password: thisIs1StrongPassword
      username: root
    type: Opaque
