en:
  labels:
    backends: Backends
    clickhouse:
      clientCaCertificates: Client CA Certificates
      clusterTopology: Cluster Topology
      deletionPolicy: Deletion Policy
      deploymentMode: Deployment Mode
      general: General
      storage: Persistent Storage
      version: Version
    logs:
      clickhouse: ClickHouse
      title: Logs
      victoriaLogs: VictoriaLogs
    metrics:
      thanos:
        compact: Compact
        query: Query
        receive: Receive
        ruler: Ruler
        s3: S3 Storage
        store: Store
        title: Thanos
      title: Metrics
      victoriaMetrics:
        cluster: Cluster
        licence: Licence
        title: VictoriaMetrics
    s3:
      accessKey: Access Key
      bucket: Bucket
      endpoint: Endpoint
      prefix: Prefix
      region: Region
      secretKey: Secret Key
    traces:
      clickhouse: ClickHouse
      title: Traces
