en:
  labels:
    logs:
      title: Logs
      clickhouse: ClickHouse
    metrics:
      title: Metrics
      thanos:
        title: Thanos
        compact: Compact
        query: Query
        receive: Receive
        ruler: Ruler
        s3: S3 Storage
        store: Store
    traces:
      title: Traces
      clickhouse: ClickHouse
    clickhouse:
      clusterTopology: Cluster Topology
      clientCaCertificates: Client CA Certificates
      deletionPolicy: Deletion Policy
      deploymentMode: Deployment Mode
      general: General
      storage: Persistent Storage
      version: Version
    s3:
      accessKey: Access Key
      bucket: Bucket
      endpoint: Endpoint
      prefix: Prefix
      region: Region
      secretKey: Secret Key
  steps:
  - label: Options
