{{- if .Values.spec.configuration }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubedbcom-hanadb-editor-options.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedbcom-hanadb-editor-options.labels" . | nindent 4 }}
data:
  global.ini: {{ .Values.spec.configuration | b64enc | quote }}
{{- end }}
