//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Free Trial License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Free-Trial-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "kmodules.xyz/offshoot-api/api/v1"
	v1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSecret) DeepCopyInto(out *AuthSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSecret.
func (in *AuthSecret) DeepCopy() *AuthSecret {
	if in == nil {
		return nil
	}
	out := new(AuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Azure) DeepCopyInto(out *Azure) {
	*out = *in
	out.Spec = in.Spec
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AzureAuth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Azure.
func (in *Azure) DeepCopy() *Azure {
	if in == nil {
		return nil
	}
	out := new(Azure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuth) DeepCopyInto(out *AzureAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuth.
func (in *AzureAuth) DeepCopy() *AzureAuth {
	if in == nil {
		return nil
	}
	out := new(AzureAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2) DeepCopyInto(out *B2) {
	*out = *in
	out.Spec = in.Spec
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(B2Auth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2.
func (in *B2) DeepCopy() *B2 {
	if in == nil {
		return nil
	}
	out := new(B2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B2Auth) DeepCopyInto(out *B2Auth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B2Auth.
func (in *B2Auth) DeepCopy() *B2Auth {
	if in == nil {
		return nil
	}
	out := new(B2Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchNode) DeepCopyInto(out *ElasticsearchNode) {
	*out = *in
	out.Persistence = in.Persistence
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchNode.
func (in *ElasticsearchNode) DeepCopy() *ElasticsearchNode {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchTopology) DeepCopyInto(out *ElasticsearchTopology) {
	*out = *in
	out.Master = in.Master
	out.Data = in.Data
	out.Ingest = in.Ingest
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchTopology.
func (in *ElasticsearchTopology) DeepCopy() *ElasticsearchTopology {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAlert) DeepCopyInto(out *FixedAlert) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAlert.
func (in *FixedAlert) DeepCopy() *FixedAlert {
	if in == nil {
		return nil
	}
	out := new(FixedAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatValAlertConfig) DeepCopyInto(out *FloatValAlertConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatValAlertConfig.
func (in *FloatValAlertConfig) DeepCopy() *FloatValAlertConfig {
	if in == nil {
		return nil
	}
	out := new(FloatValAlertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCS) DeepCopyInto(out *GCS) {
	*out = *in
	out.Spec = in.Spec
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(GCSAuth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCS.
func (in *GCS) DeepCopy() *GCS {
	if in == nil {
		return nil
	}
	out := new(GCS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSAuth) DeepCopyInto(out *GCSAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSAuth.
func (in *GCSAuth) DeepCopy() *GCSAuth {
	if in == nil {
		return nil
	}
	out := new(GCSAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntValAlert) DeepCopyInto(out *IntValAlert) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntValAlert.
func (in *IntValAlert) DeepCopy() *IntValAlert {
	if in == nil {
		return nil
	}
	out := new(IntValAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaNode) DeepCopyInto(out *KafkaNode) {
	*out = *in
	out.Persistence = in.Persistence
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaNode.
func (in *KafkaNode) DeepCopy() *KafkaNode {
	if in == nil {
		return nil
	}
	out := new(KafkaNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTopology) DeepCopyInto(out *KafkaTopology) {
	*out = *in
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(KafkaNode)
		**out = **in
	}
	if in.Broker != nil {
		in, out := &in.Broker, &out.Broker
		*out = new(KafkaNode)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTopology.
func (in *KafkaTopology) DeepCopy() *KafkaTopology {
	if in == nil {
		return nil
	}
	out := new(KafkaTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomElasticsearchEditorOptions) DeepCopyInto(out *KubedbcomElasticsearchEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomElasticsearchEditorOptions.
func (in *KubedbcomElasticsearchEditorOptions) DeepCopy() *KubedbcomElasticsearchEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomElasticsearchEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomElasticsearchEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomElasticsearchEditorOptionsList) DeepCopyInto(out *KubedbcomElasticsearchEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomElasticsearchEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomElasticsearchEditorOptionsList.
func (in *KubedbcomElasticsearchEditorOptionsList) DeepCopy() *KubedbcomElasticsearchEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomElasticsearchEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomElasticsearchEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomElasticsearchEditorOptionsSpec) DeepCopyInto(out *KubedbcomElasticsearchEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomElasticsearchEditorOptionsSpec.
func (in *KubedbcomElasticsearchEditorOptionsSpec) DeepCopy() *KubedbcomElasticsearchEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomElasticsearchEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomElasticsearchEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomElasticsearchEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(ElasticsearchTopology)
		**out = **in
	}
	out.StorageClass = in.StorageClass
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(Persistence)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomElasticsearchEditorOptionsSpecSpec.
func (in *KubedbcomElasticsearchEditorOptionsSpecSpec) DeepCopy() *KubedbcomElasticsearchEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomElasticsearchEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomKafkaEditorOptions) DeepCopyInto(out *KubedbcomKafkaEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomKafkaEditorOptions.
func (in *KubedbcomKafkaEditorOptions) DeepCopy() *KubedbcomKafkaEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomKafkaEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomKafkaEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomKafkaEditorOptionsList) DeepCopyInto(out *KubedbcomKafkaEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomKafkaEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomKafkaEditorOptionsList.
func (in *KubedbcomKafkaEditorOptionsList) DeepCopy() *KubedbcomKafkaEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomKafkaEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomKafkaEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomKafkaEditorOptionsSpec) DeepCopyInto(out *KubedbcomKafkaEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomKafkaEditorOptionsSpec.
func (in *KubedbcomKafkaEditorOptionsSpec) DeepCopy() *KubedbcomKafkaEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomKafkaEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomKafkaEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomKafkaEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(KafkaTopology)
		(*in).DeepCopyInto(*out)
	}
	out.StorageClass = in.StorageClass
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(Persistence)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomKafkaEditorOptionsSpecSpec.
func (in *KubedbcomKafkaEditorOptionsSpecSpec) DeepCopy() *KubedbcomKafkaEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomKafkaEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMariadbEditorOptions) DeepCopyInto(out *KubedbcomMariadbEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMariadbEditorOptions.
func (in *KubedbcomMariadbEditorOptions) DeepCopy() *KubedbcomMariadbEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMariadbEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMariadbEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMariadbEditorOptionsList) DeepCopyInto(out *KubedbcomMariadbEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomMariadbEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMariadbEditorOptionsList.
func (in *KubedbcomMariadbEditorOptionsList) DeepCopy() *KubedbcomMariadbEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMariadbEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMariadbEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMariadbEditorOptionsSpec) DeepCopyInto(out *KubedbcomMariadbEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMariadbEditorOptionsSpec.
func (in *KubedbcomMariadbEditorOptionsSpec) DeepCopy() *KubedbcomMariadbEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMariadbEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMariadbEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomMariadbEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.StorageClass = in.StorageClass
	out.Persistence = in.Persistence
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMariadbEditorOptionsSpecSpec.
func (in *KubedbcomMariadbEditorOptionsSpecSpec) DeepCopy() *KubedbcomMariadbEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMariadbEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMemcachedEditorOptions) DeepCopyInto(out *KubedbcomMemcachedEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMemcachedEditorOptions.
func (in *KubedbcomMemcachedEditorOptions) DeepCopy() *KubedbcomMemcachedEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMemcachedEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMemcachedEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMemcachedEditorOptionsList) DeepCopyInto(out *KubedbcomMemcachedEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomMemcachedEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMemcachedEditorOptionsList.
func (in *KubedbcomMemcachedEditorOptionsList) DeepCopy() *KubedbcomMemcachedEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMemcachedEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMemcachedEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMemcachedEditorOptionsSpec) DeepCopyInto(out *KubedbcomMemcachedEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMemcachedEditorOptionsSpec.
func (in *KubedbcomMemcachedEditorOptionsSpec) DeepCopy() *KubedbcomMemcachedEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMemcachedEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMemcachedEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomMemcachedEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMemcachedEditorOptionsSpecSpec.
func (in *KubedbcomMemcachedEditorOptionsSpecSpec) DeepCopy() *KubedbcomMemcachedEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMemcachedEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMongodbEditorOptions) DeepCopyInto(out *KubedbcomMongodbEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMongodbEditorOptions.
func (in *KubedbcomMongodbEditorOptions) DeepCopy() *KubedbcomMongodbEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMongodbEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMongodbEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMongodbEditorOptionsList) DeepCopyInto(out *KubedbcomMongodbEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomMongodbEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMongodbEditorOptionsList.
func (in *KubedbcomMongodbEditorOptionsList) DeepCopy() *KubedbcomMongodbEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMongodbEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMongodbEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMongodbEditorOptionsSpec) DeepCopyInto(out *KubedbcomMongodbEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMongodbEditorOptionsSpec.
func (in *KubedbcomMongodbEditorOptionsSpec) DeepCopy() *KubedbcomMongodbEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMongodbEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMongodbEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomMongodbEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ReplicaSet = in.ReplicaSet
	out.ShardTopology = in.ShardTopology
	out.StorageClass = in.StorageClass
	out.Persistence = in.Persistence
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMongodbEditorOptionsSpecSpec.
func (in *KubedbcomMongodbEditorOptionsSpecSpec) DeepCopy() *KubedbcomMongodbEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMongodbEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMysqlEditorOptions) DeepCopyInto(out *KubedbcomMysqlEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMysqlEditorOptions.
func (in *KubedbcomMysqlEditorOptions) DeepCopy() *KubedbcomMysqlEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMysqlEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMysqlEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMysqlEditorOptionsList) DeepCopyInto(out *KubedbcomMysqlEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomMysqlEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMysqlEditorOptionsList.
func (in *KubedbcomMysqlEditorOptionsList) DeepCopy() *KubedbcomMysqlEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMysqlEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomMysqlEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMysqlEditorOptionsSpec) DeepCopyInto(out *KubedbcomMysqlEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMysqlEditorOptionsSpec.
func (in *KubedbcomMysqlEditorOptionsSpec) DeepCopy() *KubedbcomMysqlEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMysqlEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomMysqlEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomMysqlEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.InnoDBCluster = in.InnoDBCluster
	out.StorageClass = in.StorageClass
	out.Persistence = in.Persistence
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomMysqlEditorOptionsSpecSpec.
func (in *KubedbcomMysqlEditorOptionsSpecSpec) DeepCopy() *KubedbcomMysqlEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomMysqlEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPgbouncerEditorOptions) DeepCopyInto(out *KubedbcomPgbouncerEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPgbouncerEditorOptions.
func (in *KubedbcomPgbouncerEditorOptions) DeepCopy() *KubedbcomPgbouncerEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPgbouncerEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomPgbouncerEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPgbouncerEditorOptionsList) DeepCopyInto(out *KubedbcomPgbouncerEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomPgbouncerEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPgbouncerEditorOptionsList.
func (in *KubedbcomPgbouncerEditorOptionsList) DeepCopy() *KubedbcomPgbouncerEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPgbouncerEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomPgbouncerEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPgbouncerEditorOptionsSpec) DeepCopyInto(out *KubedbcomPgbouncerEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPgbouncerEditorOptionsSpec.
func (in *KubedbcomPgbouncerEditorOptionsSpec) DeepCopy() *KubedbcomPgbouncerEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPgbouncerEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPgbouncerEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomPgbouncerEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]v1alpha2.Databases, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPgbouncerEditorOptionsSpecSpec.
func (in *KubedbcomPgbouncerEditorOptionsSpecSpec) DeepCopy() *KubedbcomPgbouncerEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPgbouncerEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPostgresEditorOptions) DeepCopyInto(out *KubedbcomPostgresEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPostgresEditorOptions.
func (in *KubedbcomPostgresEditorOptions) DeepCopy() *KubedbcomPostgresEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPostgresEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomPostgresEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPostgresEditorOptionsList) DeepCopyInto(out *KubedbcomPostgresEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomPostgresEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPostgresEditorOptionsList.
func (in *KubedbcomPostgresEditorOptionsList) DeepCopy() *KubedbcomPostgresEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPostgresEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomPostgresEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPostgresEditorOptionsSpec) DeepCopyInto(out *KubedbcomPostgresEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPostgresEditorOptionsSpec.
func (in *KubedbcomPostgresEditorOptionsSpec) DeepCopy() *KubedbcomPostgresEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPostgresEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomPostgresEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomPostgresEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.StorageClass = in.StorageClass
	out.Persistence = in.Persistence
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomPostgresEditorOptionsSpecSpec.
func (in *KubedbcomPostgresEditorOptionsSpecSpec) DeepCopy() *KubedbcomPostgresEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomPostgresEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomProxysqlEditorMonitoring) DeepCopyInto(out *KubedbcomProxysqlEditorMonitoring) {
	*out = *in
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorLabels)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomProxysqlEditorMonitoring.
func (in *KubedbcomProxysqlEditorMonitoring) DeepCopy() *KubedbcomProxysqlEditorMonitoring {
	if in == nil {
		return nil
	}
	out := new(KubedbcomProxysqlEditorMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomProxysqlEditorOptions) DeepCopyInto(out *KubedbcomProxysqlEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomProxysqlEditorOptions.
func (in *KubedbcomProxysqlEditorOptions) DeepCopy() *KubedbcomProxysqlEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomProxysqlEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomProxysqlEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomProxysqlEditorOptionsList) DeepCopyInto(out *KubedbcomProxysqlEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomProxysqlEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomProxysqlEditorOptionsList.
func (in *KubedbcomProxysqlEditorOptionsList) DeepCopy() *KubedbcomProxysqlEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomProxysqlEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomProxysqlEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomProxysqlEditorOptionsSpec) DeepCopyInto(out *KubedbcomProxysqlEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomProxysqlEditorOptionsSpec.
func (in *KubedbcomProxysqlEditorOptionsSpec) DeepCopy() *KubedbcomProxysqlEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomProxysqlEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomProxysqlEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomProxysqlEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomProxysqlEditorOptionsSpecSpec.
func (in *KubedbcomProxysqlEditorOptionsSpecSpec) DeepCopy() *KubedbcomProxysqlEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomProxysqlEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomRedisEditorOptions) DeepCopyInto(out *KubedbcomRedisEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomRedisEditorOptions.
func (in *KubedbcomRedisEditorOptions) DeepCopy() *KubedbcomRedisEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubedbcomRedisEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomRedisEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomRedisEditorOptionsList) DeepCopyInto(out *KubedbcomRedisEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedbcomRedisEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomRedisEditorOptionsList.
func (in *KubedbcomRedisEditorOptionsList) DeepCopy() *KubedbcomRedisEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubedbcomRedisEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedbcomRedisEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomRedisEditorOptionsSpec) DeepCopyInto(out *KubedbcomRedisEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomRedisEditorOptionsSpec.
func (in *KubedbcomRedisEditorOptionsSpec) DeepCopy() *KubedbcomRedisEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomRedisEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedbcomRedisEditorOptionsSpecSpec) DeepCopyInto(out *KubedbcomRedisEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Cluster = in.Cluster
	out.SentinelRef = in.SentinelRef
	out.StorageClass = in.StorageClass
	out.Persistence = in.Persistence
	in.Resources.DeepCopyInto(&out.Resources)
	out.AuthSecret = in.AuthSecret
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedbcomRedisEditorOptionsSpecSpec.
func (in *KubedbcomRedisEditorOptionsSpecSpec) DeepCopy() *KubedbcomRedisEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedbcomRedisEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubevaultcomVaultserverEditorOptions) DeepCopyInto(out *KubevaultcomVaultserverEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubevaultcomVaultserverEditorOptions.
func (in *KubevaultcomVaultserverEditorOptions) DeepCopy() *KubevaultcomVaultserverEditorOptions {
	if in == nil {
		return nil
	}
	out := new(KubevaultcomVaultserverEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubevaultcomVaultserverEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubevaultcomVaultserverEditorOptionsList) DeepCopyInto(out *KubevaultcomVaultserverEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubevaultcomVaultserverEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubevaultcomVaultserverEditorOptionsList.
func (in *KubevaultcomVaultserverEditorOptionsList) DeepCopy() *KubevaultcomVaultserverEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(KubevaultcomVaultserverEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubevaultcomVaultserverEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubevaultcomVaultserverEditorOptionsSpec) DeepCopyInto(out *KubevaultcomVaultserverEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	in.Form.DeepCopyInto(&out.Form)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubevaultcomVaultserverEditorOptionsSpec.
func (in *KubevaultcomVaultserverEditorOptionsSpec) DeepCopy() *KubevaultcomVaultserverEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(KubevaultcomVaultserverEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubevaultcomVaultserverEditorOptionsSpecSpec) DeepCopyInto(out *KubevaultcomVaultserverEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Backend = in.Backend
	out.Unsealer = in.Unsealer
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubevaultcomVaultserverEditorOptionsSpecSpec.
func (in *KubevaultcomVaultserverEditorOptionsSpecSpec) DeepCopy() *KubevaultcomVaultserverEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubevaultcomVaultserverEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBConfigServer) DeepCopyInto(out *MongoDBConfigServer) {
	*out = *in
	out.Persistence = in.Persistence
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBConfigServer.
func (in *MongoDBConfigServer) DeepCopy() *MongoDBConfigServer {
	if in == nil {
		return nil
	}
	out := new(MongoDBConfigServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBMongos) DeepCopyInto(out *MongoDBMongos) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBMongos.
func (in *MongoDBMongos) DeepCopy() *MongoDBMongos {
	if in == nil {
		return nil
	}
	out := new(MongoDBMongos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBReplicaSet) DeepCopyInto(out *MongoDBReplicaSet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBReplicaSet.
func (in *MongoDBReplicaSet) DeepCopy() *MongoDBReplicaSet {
	if in == nil {
		return nil
	}
	out := new(MongoDBReplicaSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBShard) DeepCopyInto(out *MongoDBShard) {
	*out = *in
	out.Persistence = in.Persistence
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBShard.
func (in *MongoDBShard) DeepCopy() *MongoDBShard {
	if in == nil {
		return nil
	}
	out := new(MongoDBShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBShardTopology) DeepCopyInto(out *MongoDBShardTopology) {
	*out = *in
	out.Shard = in.Shard
	out.ConfigServer = in.ConfigServer
	out.Mongos = in.Mongos
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBShardTopology.
func (in *MongoDBShardTopology) DeepCopy() *MongoDBShardTopology {
	if in == nil {
		return nil
	}
	out := new(MongoDBShardTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorLabels)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLInnoDBCluster) DeepCopyInto(out *MySQLInnoDBCluster) {
	*out = *in
	out.Router = in.Router
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLInnoDBCluster.
func (in *MySQLInnoDBCluster) DeepCopy() *MySQLInnoDBCluster {
	if in == nil {
		return nil
	}
	out := new(MySQLInnoDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLRouter) DeepCopyInto(out *MySQLRouter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLRouter.
func (in *MySQLRouter) DeepCopy() *MySQLRouter {
	if in == nil {
		return nil
	}
	out := new(MySQLRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsManagerAlert) DeepCopyInto(out *OpsManagerAlert) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsManagerAlert.
func (in *OpsManagerAlert) DeepCopy() *OpsManagerAlert {
	if in == nil {
		return nil
	}
	out := new(OpsManagerAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsManagerAlertRules) DeepCopyInto(out *OpsManagerAlertRules) {
	*out = *in
	out.OpsRequestOnProgress = in.OpsRequestOnProgress
	out.OpsRequestStatusProgressingToLong = in.OpsRequestStatusProgressingToLong
	out.OpsRequestFailed = in.OpsRequestFailed
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsManagerAlertRules.
func (in *OpsManagerAlertRules) DeepCopy() *OpsManagerAlertRules {
	if in == nil {
		return nil
	}
	out := new(OpsManagerAlertRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusExporter) DeepCopyInto(out *PrometheusExporter) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusExporter.
func (in *PrometheusExporter) DeepCopy() *PrometheusExporter {
	if in == nil {
		return nil
	}
	out := new(PrometheusExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerAlert) DeepCopyInto(out *ProvisionerAlert) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerAlert.
func (in *ProvisionerAlert) DeepCopy() *ProvisionerAlert {
	if in == nil {
		return nil
	}
	out := new(ProvisionerAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerAlertRules) DeepCopyInto(out *ProvisionerAlertRules) {
	*out = *in
	out.AppPhaseNotReady = in.AppPhaseNotReady
	out.AppPhaseCritical = in.AppPhaseCritical
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerAlertRules.
func (in *ProvisionerAlertRules) DeepCopy() *ProvisionerAlertRules {
	if in == nil {
		return nil
	}
	out := new(ProvisionerAlertRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisCluster) DeepCopyInto(out *RedisCluster) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisCluster.
func (in *RedisCluster) DeepCopy() *RedisCluster {
	if in == nil {
		return nil
	}
	out := new(RedisCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryBackend) DeepCopyInto(out *RepositoryBackend) {
	*out = *in
	in.S3.DeepCopyInto(&out.S3)
	in.Azure.DeepCopyInto(&out.Azure)
	in.GCS.DeepCopyInto(&out.GCS)
	in.Swift.DeepCopyInto(&out.Swift)
	in.B2.DeepCopyInto(&out.B2)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryBackend.
func (in *RepositoryBackend) DeepCopy() *RepositoryBackend {
	if in == nil {
		return nil
	}
	out := new(RepositoryBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3) DeepCopyInto(out *S3) {
	*out = *in
	out.Spec = in.Spec
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(S3Auth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3.
func (in *S3) DeepCopy() *S3 {
	if in == nil {
		return nil
	}
	out := new(S3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Auth) DeepCopyInto(out *S3Auth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Auth.
func (in *S3Auth) DeepCopy() *S3Auth {
	if in == nil {
		return nil
	}
	out := new(S3Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaManagerAlert) DeepCopyInto(out *SchemaManagerAlert) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaManagerAlert.
func (in *SchemaManagerAlert) DeepCopy() *SchemaManagerAlert {
	if in == nil {
		return nil
	}
	out := new(SchemaManagerAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaManagerAlertRules) DeepCopyInto(out *SchemaManagerAlertRules) {
	*out = *in
	out.SchemaPendingForTooLong = in.SchemaPendingForTooLong
	out.SchemaInProgressForTooLong = in.SchemaInProgressForTooLong
	out.SchemaTerminatingForTooLong = in.SchemaTerminatingForTooLong
	out.SchemaFailed = in.SchemaFailed
	out.SchemaExpired = in.SchemaExpired
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaManagerAlertRules.
func (in *SchemaManagerAlertRules) DeepCopy() *SchemaManagerAlertRules {
	if in == nil {
		return nil
	}
	out := new(SchemaManagerAlertRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorLabels) DeepCopyInto(out *ServiceMonitorLabels) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorLabels.
func (in *ServiceMonitorLabels) DeepCopy() *ServiceMonitorLabels {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashAlert) DeepCopyInto(out *StashAlert) {
	*out = *in
	out.Rules = in.Rules
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashAlert.
func (in *StashAlert) DeepCopy() *StashAlert {
	if in == nil {
		return nil
	}
	out := new(StashAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashAlertRules) DeepCopyInto(out *StashAlertRules) {
	*out = *in
	out.BackupSessionFailed = in.BackupSessionFailed
	out.RestoreSessionFailed = in.RestoreSessionFailed
	out.NoBackupSessionForTooLong = in.NoBackupSessionForTooLong
	out.RepositoryCorrupted = in.RepositoryCorrupted
	out.RepositoryStorageRunningLow = in.RepositoryStorageRunningLow
	out.BackupSessionPeriodTooLong = in.BackupSessionPeriodTooLong
	out.RestoreSessionPeriodTooLong = in.RestoreSessionPeriodTooLong
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashAlertRules.
func (in *StashAlertRules) DeepCopy() *StashAlertRules {
	if in == nil {
		return nil
	}
	out := new(StashAlertRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRepositoryEditorOptions) DeepCopyInto(out *StashappscodecomRepositoryEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRepositoryEditorOptions.
func (in *StashappscodecomRepositoryEditorOptions) DeepCopy() *StashappscodecomRepositoryEditorOptions {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRepositoryEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StashappscodecomRepositoryEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRepositoryEditorOptionsList) DeepCopyInto(out *StashappscodecomRepositoryEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StashappscodecomRepositoryEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRepositoryEditorOptionsList.
func (in *StashappscodecomRepositoryEditorOptionsList) DeepCopy() *StashappscodecomRepositoryEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRepositoryEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StashappscodecomRepositoryEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRepositoryEditorOptionsSpec) DeepCopyInto(out *StashappscodecomRepositoryEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRepositoryEditorOptionsSpec.
func (in *StashappscodecomRepositoryEditorOptionsSpec) DeepCopy() *StashappscodecomRepositoryEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRepositoryEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRepositoryEditorOptionsSpecSpec) DeepCopyInto(out *StashappscodecomRepositoryEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.AuthSecret = in.AuthSecret
	in.Backend.DeepCopyInto(&out.Backend)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRepositoryEditorOptionsSpecSpec.
func (in *StashappscodecomRepositoryEditorOptionsSpecSpec) DeepCopy() *StashappscodecomRepositoryEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRepositoryEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRestoreSessionEditorOptions) DeepCopyInto(out *StashappscodecomRestoreSessionEditorOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRestoreSessionEditorOptions.
func (in *StashappscodecomRestoreSessionEditorOptions) DeepCopy() *StashappscodecomRestoreSessionEditorOptions {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRestoreSessionEditorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StashappscodecomRestoreSessionEditorOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRestoreSessionEditorOptionsList) DeepCopyInto(out *StashappscodecomRestoreSessionEditorOptionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StashappscodecomRestoreSessionEditorOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRestoreSessionEditorOptionsList.
func (in *StashappscodecomRestoreSessionEditorOptionsList) DeepCopy() *StashappscodecomRestoreSessionEditorOptionsList {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRestoreSessionEditorOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StashappscodecomRestoreSessionEditorOptionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRestoresessionEditorOptionsSpec) DeepCopyInto(out *StashappscodecomRestoresessionEditorOptionsSpec) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRestoresessionEditorOptionsSpec.
func (in *StashappscodecomRestoresessionEditorOptionsSpec) DeepCopy() *StashappscodecomRestoresessionEditorOptionsSpec {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRestoresessionEditorOptionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StashappscodecomRestoresessionEditorOptionsSpecSpec) DeepCopyInto(out *StashappscodecomRestoresessionEditorOptionsSpecSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InterimVolumeTemplate != nil {
		in, out := &in.InterimVolumeTemplate, &out.InterimVolumeTemplate
		*out = new(v1.PersistentVolumeClaim)
		(*in).DeepCopyInto(*out)
	}
	out.Repository = in.Repository
	in.RuntimeSettings.DeepCopyInto(&out.RuntimeSettings)
	out.Target = in.Target
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StashappscodecomRestoresessionEditorOptionsSpecSpec.
func (in *StashappscodecomRestoresessionEditorOptionsSpecSpec) DeepCopy() *StashappscodecomRestoresessionEditorOptionsSpecSpec {
	if in == nil {
		return nil
	}
	out := new(StashappscodecomRestoresessionEditorOptionsSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClass) DeepCopyInto(out *StorageClass) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClass.
func (in *StorageClass) DeepCopy() *StorageClass {
	if in == nil {
		return nil
	}
	out := new(StorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringValAlert) DeepCopyInto(out *StringValAlert) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringValAlert.
func (in *StringValAlert) DeepCopy() *StringValAlert {
	if in == nil {
		return nil
	}
	out := new(StringValAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Swift) DeepCopyInto(out *Swift) {
	*out = *in
	out.Spec = in.Spec
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(SwiftAuth)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Swift.
func (in *Swift) DeepCopy() *Swift {
	if in == nil {
		return nil
	}
	out := new(Swift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftAuth) DeepCopyInto(out *SwiftAuth) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftAuth.
func (in *SwiftAuth) DeepCopy() *SwiftAuth {
	if in == nil {
		return nil
	}
	out := new(SwiftAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnsealerCredentialSecret) DeepCopyInto(out *UnsealerCredentialSecret) {
	*out = *in
	out.AwsKmsSsm = in.AwsKmsSsm
	out.AzureKeyVault = in.AzureKeyVault
	out.GoogleKmsGcs = in.GoogleKmsGcs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnsealerCredentialSecret.
func (in *UnsealerCredentialSecret) DeepCopy() *UnsealerCredentialSecret {
	if in == nil {
		return nil
	}
	out := new(UnsealerCredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackend) DeepCopyInto(out *VaultserverBackend) {
	*out = *in
	out.TLSSecret = in.TLSSecret
	out.CredentialSecret = in.CredentialSecret
	out.Provider = in.Provider
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackend.
func (in *VaultserverBackend) DeepCopy() *VaultserverBackend {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialAzure) DeepCopyInto(out *VaultserverBackendCredentialAzure) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialAzure.
func (in *VaultserverBackendCredentialAzure) DeepCopy() *VaultserverBackendCredentialAzure {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialAzure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialConsul) DeepCopyInto(out *VaultserverBackendCredentialConsul) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialConsul.
func (in *VaultserverBackendCredentialConsul) DeepCopy() *VaultserverBackendCredentialConsul {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialConsul)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialDynamodb) DeepCopyInto(out *VaultserverBackendCredentialDynamodb) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialDynamodb.
func (in *VaultserverBackendCredentialDynamodb) DeepCopy() *VaultserverBackendCredentialDynamodb {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialDynamodb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialEtcd) DeepCopyInto(out *VaultserverBackendCredentialEtcd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialEtcd.
func (in *VaultserverBackendCredentialEtcd) DeepCopy() *VaultserverBackendCredentialEtcd {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialGcs) DeepCopyInto(out *VaultserverBackendCredentialGcs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialGcs.
func (in *VaultserverBackendCredentialGcs) DeepCopy() *VaultserverBackendCredentialGcs {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialGcs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialMysql) DeepCopyInto(out *VaultserverBackendCredentialMysql) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialMysql.
func (in *VaultserverBackendCredentialMysql) DeepCopy() *VaultserverBackendCredentialMysql {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialMysql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialPostgresql) DeepCopyInto(out *VaultserverBackendCredentialPostgresql) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialPostgresql.
func (in *VaultserverBackendCredentialPostgresql) DeepCopy() *VaultserverBackendCredentialPostgresql {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialPostgresql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialSecret) DeepCopyInto(out *VaultserverBackendCredentialSecret) {
	*out = *in
	out.Azure = in.Azure
	out.Consul = in.Consul
	out.Dynamodb = in.Dynamodb
	out.Etcd = in.Etcd
	out.Gcs = in.Gcs
	out.Mysql = in.Mysql
	out.Postgresql = in.Postgresql
	out.S3 = in.S3
	out.Swift = in.Swift
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialSecret.
func (in *VaultserverBackendCredentialSecret) DeepCopy() *VaultserverBackendCredentialSecret {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialSecretS3) DeepCopyInto(out *VaultserverBackendCredentialSecretS3) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialSecretS3.
func (in *VaultserverBackendCredentialSecretS3) DeepCopy() *VaultserverBackendCredentialSecretS3 {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialSecretS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendCredentialSecretSwift) DeepCopyInto(out *VaultserverBackendCredentialSecretSwift) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendCredentialSecretSwift.
func (in *VaultserverBackendCredentialSecretSwift) DeepCopy() *VaultserverBackendCredentialSecretSwift {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendCredentialSecretSwift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProvider) DeepCopyInto(out *VaultserverBackendProvider) {
	*out = *in
	out.Azure = in.Azure
	out.Consul = in.Consul
	out.Dynamodb = in.Dynamodb
	out.Etcd = in.Etcd
	out.Gcs = in.Gcs
	out.Inmem = in.Inmem
	out.Raft = in.Raft
	out.S3 = in.S3
	out.Swift = in.Swift
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProvider.
func (in *VaultserverBackendProvider) DeepCopy() *VaultserverBackendProvider {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderAzure) DeepCopyInto(out *VaultserverBackendProviderAzure) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderAzure.
func (in *VaultserverBackendProviderAzure) DeepCopy() *VaultserverBackendProviderAzure {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderAzure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderConsul) DeepCopyInto(out *VaultserverBackendProviderConsul) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderConsul.
func (in *VaultserverBackendProviderConsul) DeepCopy() *VaultserverBackendProviderConsul {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderConsul)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderDynamodb) DeepCopyInto(out *VaultserverBackendProviderDynamodb) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderDynamodb.
func (in *VaultserverBackendProviderDynamodb) DeepCopy() *VaultserverBackendProviderDynamodb {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderDynamodb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderEtcd) DeepCopyInto(out *VaultserverBackendProviderEtcd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderEtcd.
func (in *VaultserverBackendProviderEtcd) DeepCopy() *VaultserverBackendProviderEtcd {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderGcs) DeepCopyInto(out *VaultserverBackendProviderGcs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderGcs.
func (in *VaultserverBackendProviderGcs) DeepCopy() *VaultserverBackendProviderGcs {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderGcs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderInmem) DeepCopyInto(out *VaultserverBackendProviderInmem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderInmem.
func (in *VaultserverBackendProviderInmem) DeepCopy() *VaultserverBackendProviderInmem {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderInmem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderRaft) DeepCopyInto(out *VaultserverBackendProviderRaft) {
	*out = *in
	out.StorageClass = in.StorageClass
	out.Persistence = in.Persistence
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderRaft.
func (in *VaultserverBackendProviderRaft) DeepCopy() *VaultserverBackendProviderRaft {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderRaft)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderS3) DeepCopyInto(out *VaultserverBackendProviderS3) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderS3.
func (in *VaultserverBackendProviderS3) DeepCopy() *VaultserverBackendProviderS3 {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendProviderSwift) DeepCopyInto(out *VaultserverBackendProviderSwift) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendProviderSwift.
func (in *VaultserverBackendProviderSwift) DeepCopy() *VaultserverBackendProviderSwift {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendProviderSwift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendTLSConsul) DeepCopyInto(out *VaultserverBackendTLSConsul) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendTLSConsul.
func (in *VaultserverBackendTLSConsul) DeepCopy() *VaultserverBackendTLSConsul {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendTLSConsul)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendTLSMysql) DeepCopyInto(out *VaultserverBackendTLSMysql) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendTLSMysql.
func (in *VaultserverBackendTLSMysql) DeepCopy() *VaultserverBackendTLSMysql {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendTLSMysql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverBackendTLSSecret) DeepCopyInto(out *VaultserverBackendTLSSecret) {
	*out = *in
	out.Consul = in.Consul
	out.Mysql = in.Mysql
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverBackendTLSSecret.
func (in *VaultserverBackendTLSSecret) DeepCopy() *VaultserverBackendTLSSecret {
	if in == nil {
		return nil
	}
	out := new(VaultserverBackendTLSSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverCredentialAwsKmsSsm) DeepCopyInto(out *VaultserverCredentialAwsKmsSsm) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverCredentialAwsKmsSsm.
func (in *VaultserverCredentialAwsKmsSsm) DeepCopy() *VaultserverCredentialAwsKmsSsm {
	if in == nil {
		return nil
	}
	out := new(VaultserverCredentialAwsKmsSsm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverCredentialAzureKeyVault) DeepCopyInto(out *VaultserverCredentialAzureKeyVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverCredentialAzureKeyVault.
func (in *VaultserverCredentialAzureKeyVault) DeepCopy() *VaultserverCredentialAzureKeyVault {
	if in == nil {
		return nil
	}
	out := new(VaultserverCredentialAzureKeyVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverCredentialSecretGoogleKmsGcs) DeepCopyInto(out *VaultserverCredentialSecretGoogleKmsGcs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverCredentialSecretGoogleKmsGcs.
func (in *VaultserverCredentialSecretGoogleKmsGcs) DeepCopy() *VaultserverCredentialSecretGoogleKmsGcs {
	if in == nil {
		return nil
	}
	out := new(VaultserverCredentialSecretGoogleKmsGcs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverUnsealer) DeepCopyInto(out *VaultserverUnsealer) {
	*out = *in
	out.CredentialSecret = in.CredentialSecret
	out.Mode = in.Mode
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverUnsealer.
func (in *VaultserverUnsealer) DeepCopy() *VaultserverUnsealer {
	if in == nil {
		return nil
	}
	out := new(VaultserverUnsealer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverUnsealerMode) DeepCopyInto(out *VaultserverUnsealerMode) {
	*out = *in
	out.AwsKmsSsm = in.AwsKmsSsm
	out.AzureKeyVault = in.AzureKeyVault
	out.GoogleKmsGcs = in.GoogleKmsGcs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverUnsealerMode.
func (in *VaultserverUnsealerMode) DeepCopy() *VaultserverUnsealerMode {
	if in == nil {
		return nil
	}
	out := new(VaultserverUnsealerMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverUnsealerModeAwsKmsSsm) DeepCopyInto(out *VaultserverUnsealerModeAwsKmsSsm) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverUnsealerModeAwsKmsSsm.
func (in *VaultserverUnsealerModeAwsKmsSsm) DeepCopy() *VaultserverUnsealerModeAwsKmsSsm {
	if in == nil {
		return nil
	}
	out := new(VaultserverUnsealerModeAwsKmsSsm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverUnsealerModeAzureKeyVault) DeepCopyInto(out *VaultserverUnsealerModeAzureKeyVault) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverUnsealerModeAzureKeyVault.
func (in *VaultserverUnsealerModeAzureKeyVault) DeepCopy() *VaultserverUnsealerModeAzureKeyVault {
	if in == nil {
		return nil
	}
	out := new(VaultserverUnsealerModeAzureKeyVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultserverUnsealerModeGoogleKmsGcs) DeepCopyInto(out *VaultserverUnsealerModeGoogleKmsGcs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultserverUnsealerModeGoogleKmsGcs.
func (in *VaultserverUnsealerModeGoogleKmsGcs) DeepCopy() *VaultserverUnsealerModeGoogleKmsGcs {
	if in == nil {
		return nil
	}
	out := new(VaultserverUnsealerModeGoogleKmsGcs)
	in.DeepCopyInto(out)
	return out
}
