chart:
  name: courierkubedbcom-branchwork-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a BranchWork Editor
  description: BranchWork Editor
  name: BranchWork Editor by AppsCode
  shortName: BranchWork Editor
  url: https://appscode.com
release:
  name: courierkubedbcom-branchwork-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
