metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_cluster_auth_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-auth-manager
      name: cluster-auth-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cluster_gateway_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-gateway-manager
      name: cluster-gateway-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cluster_manager_hub: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-manager-hub
      name: cluster-manager-hub
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cluster_profile_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-profile-manager
      name: cluster-profile-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cluster_proxy_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-proxy-manager
      name: cluster-proxy-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_fluxcd_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: fluxcd-manager
      name: fluxcd-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_hub_cluster_robot: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: hub-cluster-robot
      name: hub-cluster-robot
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kubeslice: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubeslice
      name: kubeslice
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_license_proxyserver_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: license-proxyserver-manager
      name: license-proxyserver-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_managed_serviceaccount_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: managed-serviceaccount-manager
      name: managed-serviceaccount-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_spoke_cluster_addons: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: spoke-cluster-addons
      name: spoke-cluster-addons
      namespace: kubeops
