chart:
  name: opskubedbcom-neo4jopsrequest-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a Neo4jOpsRequest Editor
  description: Neo4jOpsRequest Editor
  name: Neo4jOpsRequest Editor by AppsCode
  shortName: Neo4jOpsRequest Editor
  url: https://appscode.com
release:
  name: opskubedbcom-neo4jopsrequest-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
