chart:
  name: catalogappscodecom-hazelcastbinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a HazelcastBinding Editor
  description: HazelcastBinding Editor
  name: HazelcastBinding Editor by AppsCode
  shortName: HazelcastBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-hazelcastbinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
