project:
  name: Milvus Editor UI Options
  shortName: Milvus Editor UI Options
  url: https://byte.builders
  description: Milvus Editor UI Options
  app: a Milvus Editor UI Options
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubedbcom-milvus-editor-options
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: kubedbcom-milvus-editor-options
  namespace: kube-system
