metadata:
  resource:
    group: storage.kubestash.com
    version: v1alpha1
    name: backupstorages
    kind: BackupStorage
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  secret_storage_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: s3-storage-cred
      namespace: ""
  storageKubestashComBackupStorage: # +doc-gen:break
    apiVersion: storage.kubestash.com/v1alpha1
    kind: BackupStorage
    metadata:
      name: s3
      namespace: demo
