chart:
  name: archiverkubedbcom-clickhousearchiver-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a ClickHouseArchiver Editor
  description: ClickHouseArchiver Editor
  name: ClickHouseArchiver Editor by AppsCode
  shortName: ClickHouseArchiver Editor
  url: https://appscode.com
release:
  name: archiverkubedbcom-clickhousearchiver-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
