metadata:
  resource:
    group: stash.appscode.com
    version: v1alpha1
    name: repositories
    kind: Repository
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  secret_repo_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: s3-repo-cred
      namespace: demo
  stashAppscodeComRepository: # +doc-gen:break
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: s3
      namespace: demo
