form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    appSuffix: ""
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          clickhouseBrokenPartsDetected:
            duration: 0m
            enabled: true
            severity: critical
          clickhouseDataPartCorrupted:
            duration: 5m
            enabled: true
            severity: warning
          clickhouseInstanceDown:
            duration: 1m
            enabled: true
            severity: critical
          clickhouseReplicationPartFetchFailed:
            duration: 5m
            enabled: true
            severity: warning
          clickhouseTooManyActiveQueries:
            duration: 1m
            enabled: true
            severity: warning
            val: 500
          clickhouseTooManyConnections:
            duration: 5m
            enabled: true
            severity: critical
            val: 400
          diskAlmostFull:
            duration: 5m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 5m
            enabled: true
            severity: warning
            val: 80
      kubeStash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: clickhouses
    kind: ClickHouse
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComClickHouseAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: ClickHouseAutoscaler
    metadata:
      name: clickhouse
      namespace: demo
  catalogAppscodeComClickHouseBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: ClickHouseBinding
    metadata:
      name: clickhouse
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: clickhouse-ca
      namespace: demo
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: clickhouse
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: clickhouse
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: clickhouse
      namespace: demo
  kubedbComClickHouse: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: ClickHouse
    metadata:
      name: clickhouse
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: clickhouse
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: clickhouse-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: clickhouse-config
      namespace: demo
