metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: clickhouses
    kind: ClickHouse
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComClickHouseAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: ClickHouseAutoscaler
    metadata:
      name: clickhouse
      namespace: demo
  catalogAppscodeComClickHouseBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: ClickHouseBinding
    metadata:
      name: clickhouse
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: clickhouse-ca
      namespace: demo
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: clickhouse
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: clickhouse
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: clickhouse
      namespace: demo
  kubedbComClickHouse: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: ClickHouse
    metadata:
      name: clickhouse
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: clickhouse
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: clickhouse-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: clickhouse-config
      namespace: demo
