chart:
  name: catalogkubedbcom-hanadbversion-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a HanaDBVersion Editor
  description: HanaDBVersion Editor
  name: HanaDBVersion Editor by AppsCode
  shortName: HanaDBVersion Editor
  url: https://appscode.com
release:
  name: catalogkubedbcom-hanadbversion-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
