metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_config_syncer: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: config-syncer
      name: config-syncer
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_csi_secrets_store_provider_azure: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: csi-secrets-store-provider-azure
      name: csi-secrets-store-provider-azure
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_external_secrets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: external-secrets
      name: external-secrets
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kubevault: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubevault
      name: kubevault
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kubevault_opscenter: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubevault-opscenter
      name: kubevault-opscenter
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_reloader: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: reloader
      name: reloader
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_sealed_secrets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: sealed-secrets
      name: sealed-secrets
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: secrets-store-csi-driver
      name: secrets-store-csi-driver
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver_provider_aws: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: secrets-store-csi-driver-provider-aws
      name: secrets-store-csi-driver-provider-aws
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver_provider_gcp: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: secrets-store-csi-driver-provider-gcp
      name: secrets-store-csi-driver-provider-gcp
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_secrets_store_csi_driver_provider_virtual_secrets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: secrets-store-csi-driver-provider-virtual-secrets
      name: secrets-store-csi-driver-provider-virtual-secrets
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_vault: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: vault
      name: vault
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_vault_secrets_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: vault-secrets-operator
      name: vault-secrets-operator
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_virtual_secrets_server: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: virtual-secrets-server
      name: virtual-secrets-server
      namespace: kubeops
