project:
  name: Weaviate Editor UI Options
  shortName: Weaviate Editor UI Options
  url: https://byte.builders
  description: Weaviate Editor UI Options
  app: a Weaviate Editor UI Options
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubedbcom-weaviate-editor-options
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: kubedbcom-weaviate-editor-options
  namespace: kube-system
