chart:
  name: catalogkubedbcom-db2version-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DB2Version Editor
  description: DB2Version Editor
  name: DB2Version Editor by AppsCode
  shortName: DB2Version Editor
  url: https://appscode.com
release:
  name: catalogkubedbcom-db2version-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
