project:
  name: Qdrant Editor UI Options
  shortName: Qdrant Editor UI Options
  url: https://byte.builders
  description: Qdrant Editor UI Options
  app: a Qdrant Editor UI Options
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubedbcom-qdrant-editor-options
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: kubedbcom-qdrant-editor-options
  namespace: kube-system
