project:
  name: TelemetryStack Editor UI Options
  shortName: TelemetryStack Editor UI Options
  url: https://byte.builders
  description: TelemetryStack Editor UI Options
  app: a TelemetryStack Editor UI Options
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: monitoringk8sappscodecom-telemetrystack-editor-options
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: monitoringk8sappscodecom-telemetrystack-editor-options
  namespace: kube-system
