metadata:
  resource:
    group: monitoring.k8s.appscode.com
    kind: TelemetryStack
    name: telemetrystacks
    scope: Cluster
    version: v1alpha1
  release:
    name: telemetry-stack
    namespace: monitoring
spec:
  metrics:
    backend: Thanos
    victoriaMetrics:
      deploymentMode: Standalone
      version: ''
      defaultRetention: 30d
      retentionStrategy: PerTierInstance
      license:
        secretName: ''
        secretKey: ''
      storage:
        size: 10Gi
        storageClassName: ''
      cluster:
        replicationFactor: 2
        insertReplicas: 2
        selectReplicas: 2
        storageReplicas: 2
    thanos:
      compact:
        storageSize: 2Gi
        retentionConfig:
        - raw: ''
          oneHour: ''
          fiveMinutes: ''
      store:
        storageSize: 2Gi
        ignoreDeletionMarksDelay: 24h
        shardingStrategy:
          type: block
          shards: 1
      query:
        replicas: 1
        queryFrontend:
          replicas: 1
      receive:
        ingesterSpec:
          name: default
          replicas: 1
          storageSize: 2Gi
          tsdbRetention: 3h
          tenancyConfig:
            tenantMatcherType: exact
            tenantHeader: THANOS-TENANT
            defaultTenantID: default
            tenantLabelName: tenant_id
        routerSpec:
          replicas: 1
          replicationFactor: 1
          externalLabels:
            receive: 'true'
      ruler:
        replicas: 1
        storageSize: 2Gi
        alertmanagerURL: ''
        additionalConfig:
          additionalArgs: []
          additionalVolumes: []
          additionalVolumeMounts: []
      s3:
        bucket: ''
        endpoint: ''
        region: ''
        prefix: ''
        accessKey: ''
        secretKey: ''
  logs:
    backend: ClickHouse
    victoriaLogs:
      deploymentMode: Standalone
      version: ''
      defaultRetention: 30d
      futureRetention: 2d
      maxDiskUsagePercent: 80
      storage:
        size: 10Gi
        storageClassName: ''
      cluster:
        insertReplicas: 2
        selectReplicas: 2
        storageReplicas: 2
    enabled: true
    deploymentMode: Standalone
    version: 24.4.1
    deletionPolicy: Delete
    storage:
      storageClassName: ''
      size: 2Gi
    clientCaCertificates: []
    clusterTopology:
      cluster:
        name: ''
        replicas: 3
        shards: 2
        persistence:
          size: 2Gi
          storageClassName: ''
      clickHouseKeeper:
        externallyManaged: false
        replicas: 3
        persistence:
          size: 2Gi
          storageClassName: ''
    s3:
      bucket: ''
      endpoint: ''
      region: ''
      prefix: ''
      accessKey: ''
      secretKey: ''
  traces:
    enabled: false
    deploymentMode: Standalone
    version: 24.4.1
    deletionPolicy: Delete
    storage:
      storageClassName: ''
      size: 2Gi
    clientCaCertificates: []
    clusterTopology:
      cluster:
        name: ''
        replicas: 3
        shards: 2
        persistence:
          size: 2Gi
          storageClassName: ''
      clickHouseKeeper:
        externallyManaged: false
        replicas: 3
        persistence:
          size: 2Gi
          storageClassName: ''
    s3:
      bucket: ''
      endpoint: ''
      region: ''
      prefix: ''
      accessKey: ''
      secretKey: ''
