chart:
  name: catalogkubedbcom-weaviateversion-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a WeaviateVersion Editor
  description: WeaviateVersion Editor
  name: WeaviateVersion Editor by AppsCode
  shortName: WeaviateVersion Editor
  url: https://appscode.com
release:
  name: catalogkubedbcom-weaviateversion-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
