form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          redisDisconnectedSlaves:
            duration: 2m
            enabled: true
            severity: warning
            val: 1
          redisDown:
            duration: 0m
            enabled: true
            severity: critical
          redisMissingMaster:
            duration: 0m
            enabled: true
            severity: critical
            val: 1
          redisRejectedConnections:
            duration: 0m
            enabled: true
            severity: warning
            val: 0
          redisTooManyConnections:
            duration: 2m
            enabled: true
            severity: warning
            val: 100
          redisTooManyMasters:
            duration: 2m
            enabled: true
            severity: critical
            val: 1
      kubeStash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
      stash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
    labels:
      release: prometheus
metadata:
  resource:
    group: kubedb.com
    version: v1
    name: redises
    kind: Redis
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComRedisAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: RedisAutoscaler
    metadata:
      name: redis
      namespace: demo
  catalogAppscodeComRedisBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: RedisBinding
    metadata:
      name: redis
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: redis-ca
      namespace: demo
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: redis
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: redis
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: redis
      namespace: demo
  gitopsKubedbComRedis: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: Redis
    metadata:
      name: redis
      namespace: demo
  gitopsKubedbComRedisSentinel_sentinel: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: RedisSentinel
    metadata:
      name: sentinel
      namespace: demo
  kubedbComRedis: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: Redis
    metadata:
      name: redis
      namespace: demo
  kubedbComRedisSentinel_sentinel: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: RedisSentinel
    metadata:
      name: sentinel
      namespace: demo
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: redis
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-config
      namespace: demo
  secret_encryption_secret: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-encryption-secret
      namespace: demo
  secret_init_repo_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-init-repo-cred
      namespace: demo
  secret_repo_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-repo-cred
      namespace: demo
  stashAppscodeComBackupConfiguration: # +doc-gen:break
    apiVersion: stash.appscode.com/v1beta1
    kind: BackupConfiguration
    metadata:
      name: redis
      namespace: demo
  stashAppscodeComRepository_init_repo: # +doc-gen:break
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: redis-init-repo
      namespace: demo
  stashAppscodeComRepository_repo: # +doc-gen:break
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: redis-repo
      namespace: demo
  stashAppscodeComRestoreSession_init: # +doc-gen:break
    apiVersion: stash.appscode.com/v1beta1
    kind: RestoreSession
    metadata:
      name: redis-init
      namespace: demo
