step:
- elements:
  - disable: isVariantAvailable
    label: Vault Server Name
    schema: schema/properties/metadata/properties/release/properties/name
    type: input
  - disable: isVariantAvailable
    label: Namespace
    loader: getResources|core|v1|namespaces
    refresh: true
    schema: schema/properties/metadata/properties/release/properties/namespace
    type: select
  - label: Vault Server Version
    loader: getVaultServerVersions|catalog.kubevault.com|v1alpha1|vaultserverversions
    schema: schema/properties/spec/properties/version
    type: select
  - buttonClass: is-light is-outlined
    label: Labels
    schema: schema/properties/spec/properties/labels
    type: object-item
  - buttonClass: is-light is-outlined
    label: Annotations
    schema: schema/properties/spec/properties/annotations
    type: object-item
  - disable:
      name: isLowAvailableStorageBackendSelected
      watchPaths:
      - schema/properties/spec/properties/backend/properties/provider/properties/type
    label: Replica Number
    schema: schema/properties/spec/properties/replicas
    type: input
  - label: Termination Policy
    options:
    - description: options.terminationPolicy.delete.description
      text: Delete
      value: Delete
    - description: options.terminationPolicy.halt.description
      text: Halt
      value: Halt
    - description: options.terminationPolicy.wipeOut.description
      text: WipeOut
      value: WipeOut
    - description: options.terminationPolicy.doNotTerminate.description
      text: DoNotTerminate
      value: DoNotTerminate
    schema: schema/properties/spec/properties/terminationPolicy
    type: radio
  - elements:
    - elements:
      - init:
          type: func
          value: setMachineToCustom
        label: Machine
        loader: getMachineListForOptions
        schema: schema/properties/spec/properties/machine
        type: select
        watcher:
          func: setResourceLimit
          paths:
          - schema/properties/spec/properties/machine
      - disable:
          name: disableLimit
          watchPaths:
          - schema/properties/spec/properties/machine
        init:
          type: func
          value: setLimitsCpuOrMem|cpu
        label: CPU
        schema: schema/properties/spec/properties/resources/properties/limits/properties/cpu
        type: input
      - disable:
          name: disableLimit
          watchPaths:
          - schema/properties/spec/properties/machine
        init:
          type: func
          value: setLimitsCpuOrMem|memory
        label: Memory
        schema: schema/properties/spec/properties/resources/properties/limits/properties/memory
        type: input
      showLabels: true
      type: horizontal-layout
    label: Machine Profile
    showLabels: true
    type: block-layout
  - elements:
    - elements:
      - label: Provider
        options:
        - azure
        - consul
        - dynamodb
        - etcd
        - gcs
        - inmem
        - mysql
        - postgresql
        - raft
        - s3
        - swift
        schema: schema/properties/spec/properties/backend/properties/provider/properties/type
        type: select
        watcher:
          func: onBackendTypeChange
          paths:
          - schema/properties/spec/properties/backend/properties/provider/properties/type
      - elements:
        - label: Account Name
          schema: schema/properties/spec/properties/backend/properties/provider/properties/azure/properties/accountName
          type: input
        if:
          name: isEqualToModelPathValue|azure|/spec/backend/provider/type
          type: function
        type: block-layout
      - elements:
        - label: Address
          schema: schema/properties/spec/properties/backend/properties/provider/properties/consul/properties/address
          type: input
        - label: Path
          schema: schema/properties/spec/properties/backend/properties/provider/properties/consul/properties/path
          type: input
        if:
          name: isEqualToModelPathValue|consul|/spec/backend/provider/type
          type: function
        type: block-layout
      - elements:
        - label: Address
          schema: schema/properties/spec/properties/backend/properties/provider/properties/etcd/properties/address
          type: input
        if:
          name: isEqualToModelPathValue|etcd|/spec/backend/provider/type
          type: function
        type: block-layout
      - elements:
        - label: Bucket
          schema: schema/properties/spec/properties/backend/properties/provider/properties/gcs/properties/bucket
          type: input
        if:
          name: isEqualToModelPathValue|gcs|/spec/backend/provider/type
          type: function
        type: block-layout
      - elements:
        - elements:
          - label: Storage Size
            schema: schema/properties/spec/properties/backend/properties/provider/properties/raft/properties/persistence/properties/size
            type: input
          type: block-layout
        - elements:
          - label: Storage Class
            loader: getStorageClassNames|/spec/backend/provider/raft/storageClass/name
            schema: schema/properties/spec/properties/backend/properties/provider/properties/raft/properties/storageClass/properties/name
            type: select
          type: block-layout
        if:
          name: isEqualToModelPathValue|raft|/spec/backend/provider/type
          type: function
        type: block-layout
      - elements:
        - label: Bucket
          schema: schema/properties/spec/properties/backend/properties/provider/properties/s3/properties/bucket
          type: input
        - label: Region
          schema: schema/properties/spec/properties/backend/properties/provider/properties/s3/properties/region
          type: input
        if:
          name: isEqualToModelPathValue|s3|/spec/backend/provider/type
          type: function
        type: block-layout
      type: block-layout
    - elements:
      - label: Credential Secret
        options:
        - text: Create New Secret
          value: createNew
        - text: Use Existing Secret
          value: useExisting
        schema: temp/createBackendCredentialSecret
        type: radio
        watcher:
          func: onCreateCredentialSecretChange
          paths:
          - temp/createBackendCredentialSecret
      - if:
          name: showCredentialExistingSecretField
          type: function
        label: Secret
        loader: getSecrets
        schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/name
        type: select
      - elements:
        - label: Account Key
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/azure/properties/accountKey
          type: input
        if:
          name: showCredentialCreateSecretField|azure
          type: function
        type: block-layout
      - elements:
        - label: ACL Token
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/consul/properties/aclToken
          type: input
        if:
          name: showCredentialCreateSecretField|consul
          type: function
        type: block-layout
      - elements:
        - label: Access Key
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/dynamodb/properties/accessKey
          type: input
        - label: Secret Key
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/dynamodb/properties/secretKey
          type: input
        - label: Session Token
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/dynamodb/properties/sessionToken
          type: input
        if:
          name: showCredentialCreateSecretField|dynamodb
          type: function
        type: block-layout
      - elements:
        - label: Username
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/etcd/properties/username
          type: input
        - label: Password
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/etcd/properties/password
          type: input
        if:
          name: showCredentialCreateSecretField|etcd
          type: function
        type: block-layout
      - elements:
        - label: sa.json
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/gcs/properties/saJson
          type: editor
        if:
          name: showCredentialCreateSecretField|gcs
          type: function
        type: block-layout
      - elements:
        - label: Username
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/mysql/properties/username
          type: input
        - label: Password
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/mysql/properties/password
          type: input
        if:
          name: showCredentialCreateSecretField|mysql
          type: function
        type: block-layout
      - elements:
        - label: Connection URL
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/postgresql/properties/connectionURL
          type: input
        if:
          name: showCredentialCreateSecretField|postgresql
          type: function
        type: block-layout
      - elements:
        - label: Access Key
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/s3/properties/accessKey
          type: input
        - label: Secret Key
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/s3/properties/secretKey
          type: input
        if:
          name: showCredentialCreateSecretField|s3
          type: function
        type: block-layout
      - elements:
        - label: Username
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/swift/properties/username
          type: input
        - label: Password
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/swift/properties/password
          type: input
        - label: Auth Token
          schema: schema/properties/spec/properties/backend/properties/credentialSecret/properties/swift/properties/authToken
          type: input
        if:
          name: showCredentialCreateSecretField|swift
          type: function
        type: block-layout
      if:
        name: showCredentialSecret
        type: function
      type: block-layout
    - elements:
      - label: TLS Secret
        options:
        - text: Create New Secret
          value: createNew
        - text: Use Existing Secret
          value: useExisting
        schema: temp/createTlsSecret
        type: radio
        watcher:
          func: onCreateTlsSecretChange
          paths:
          - temp/createTlsSecret
      - if:
          name: showTlsExistingSecretField
          type: function
        label: Secret
        loader: getSecrets
        schema: schema/properties/spec/properties/backend/properties/tlsSecret/properties/name
        type: select
      - elements:
        - label: TLS CA File
          schema: schema/properties/spec/properties/backend/properties/tlsSecret/properties/mysql/properties/tlsCaFile
          type: input
        if:
          name: showTlsCreateSecretField|mysql
          type: function
        type: block-layout
      - elements:
        - label: ca.crt
          schema: schema/properties/spec/properties/backend/properties/tlsSecret/properties/consul/properties/caCrt
          type: editor
        - label: client.crt
          schema: schema/properties/spec/properties/backend/properties/tlsSecret/properties/consul/properties/clientCrt
          type: editor
        - label: client.key
          schema: schema/properties/spec/properties/backend/properties/tlsSecret/properties/consul/properties/clientKey
          type: editor
        if:
          name: showTlsCreateSecretField|consul
          type: function
        type: block-layout
      if:
        name: showTlsSecret
        type: function
      type: block-layout
    label: Backend
    showLabels: true
    type: block-layout
  - elements:
    - elements:
      - label: Unsealer Mode
        options:
        - awsKmsSsm
        - azureKeyVault
        - googleKmsGcs
        - kubernetesSecret
        schema: schema/properties/spec/properties/unsealer/properties/mode/properties/type
        type: select
      - elements:
        - label: KMS Key ID
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/awsKmsSsm/properties/kmsKeyID
          type: input
        - label: Region
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/awsKmsSsm/properties/region
          type: input
        if:
          name: isEqualToModelPathValue|awsKmsSsm|/spec/unsealer/mode/type
          type: function
        type: block-layout
      - elements:
        - label: Vault Base URL
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/azureKeyVault/properties/vaultBaseURL
          type: input
        if:
          name: isEqualToModelPathValue|azureKeyVault|/spec/unsealer/mode/type
          type: function
        type: block-layout
      - elements:
        - label: Bucket
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/googleKmsGcs/properties/bucket
          type: input
        - label: KMS Crypto Key
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/googleKmsGcs/properties/kmsCryptoKey
          type: input
        - label: KMS Key Ring
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/googleKmsGcs/properties/kmsKeyRing
          type: input
        - label: KMS Location
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/googleKmsGcs/properties/kmsLocation
          type: input
        - label: KMS Project
          schema: schema/properties/spec/properties/unsealer/properties/mode/properties/googleKmsGcs/properties/kmsProject
          type: input
        if:
          name: isEqualToModelPathValue|googleKmsGcs|/spec/unsealer/mode/type
          type: function
        type: block-layout
      type: block-layout
    - elements:
      - label: Credential Secret
        options:
        - text: Create New Secret
          value: createNew
        - text: Use Existing Secret
          value: useExisting
        schema: temp/createUnsealerCredentialSecret
        type: radio
        watcher:
          func: onCreateUnsealerCredentialSecretChange
          paths:
          - temp/createUnsealerCredentialSecret
      - if:
          name: showUnsealerCredentialExistingSecretField
          type: function
        label: Secret
        loader: getSecrets
        schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/name
        type: select
      - elements:
        - label: Access Key
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/awsKmsSsm/properties/accessKey
          type: input
        - label: Secret Key
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/awsKmsSsm/properties/secretKey
          type: input
        if:
          name: showUnsealerCredentialCreateSecretField|awsKmsSsm
          type: function
        type: block-layout
      - elements:
        - label: Client Cert
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/azureKeyVault/properties/clientCert
          type: input
        - label: Client Cert Password
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/azureKeyVault/properties/clientCertPassword
          type: input
        - label: Client Id
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/azureKeyVault/properties/clientId
          type: input
        - label: Client Secret
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/azureKeyVault/properties/clientSecret
          type: input
        if:
          name: showUnsealerCredentialCreateSecretField|azureKeyVault
          type: function
        type: block-layout
      - elements:
        - label: sa.json
          schema: schema/properties/spec/properties/unsealer/properties/credentialSecret/properties/googleKmsGcs/properties/saJson
          type: editor
        if:
          name: showUnsealerCredentialCreateSecretField|googleKmsGcs
          type: function
        type: block-layout
      if:
        name: isNotEqualToModelPathValue|kubernetesSecret|/spec/unsealer/mode/type
        type: function
      type: block-layout
    label: Unsealer
    showLabels: true
    type: block-layout
  id: options
  type: single-step-form
type: multi-step-form
