step:
- loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
  id: opscenter-backup
  elements:
  - type: checkbox
    schema: temp/properties/enabledFeatures
    label: ''
    loader: fetchFeatureSetOptions
    individualDisability: disableFeatures
    init:
      type: func
      value: getEnabledFeatures
    watcher:
      func: onEnabledFeaturesChange
      paths:
        - temp/properties/enabledFeatures
  - type: info
    customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    watcher:
      func: checkIsResourceLoaded
      paths:
        - temp/properties/isResourceLoaded
  - type: block-layout
    if:
      name: isStashPreset
      type: function
    elements:
    - type: label-element
      label: Preset Configuration
    - type: block-layout
      if:
        name: presetType|kubestash
        type: function
      elements:
      - type: select
        label: Backend Provider
        options:
        - text: Azure Blob Storage
          value: azure
        - text: Google Cloud Service
          value: gcs
        - text: AWS S3
          value: s3
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/provider
    - type: block-layout
      if:
        name: providerType|s3
        type: function
      elements:
      - type: input
        label: Bucket
        forceRequired: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/bucket
      - type: input
        label: End Point
        forceRequired: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/endpoint
      - type: input
        label: Insecure TLS
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/insecureTLS
      - type: input
        label: Prefix
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/prefix
      - type: input
        label: Region
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/region
      - type: switch
        label: Enable Storage Secret?
        init:
          type: func
          value: setStorageSecret
        schema: temp/properties/s3
        watcher:
          func: onAuthChange|s3
          paths:
            - temp/properties/s3
      - type: block-layout
        if:
          name: authEnabled
          type: function
        label: Storage Secret
        elements:
        - type: input
          label: Access Key ID
          forceRequired: true
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/auth/properties/AWS_ACCESS_KEY_ID
        - type: input
          label: Secret Access Key
          forceRequired: true
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/auth/properties/AWS_SECRET_ACCESS_KEY
        - type: input
          label: CA Cert Data
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/auth/properties/CA_CERT_DATA
    - type: block-layout
      if:
        name: providerType|azure
        type: function
      elements:
      - type: input
        label: Container
        forceRequired: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/pro perties/azure/properties/spec/properties/container
      - type: input
        label: Max Connections
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/spec/properties/maxConnections
      - type: input
        label: Prefix
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/spec/properties/prefix
      - type: switch
        label: Enable Storage Secret?
        init:
          type: func
          value: setStorageSecret
        schema: temp/properties/azure
        watcher:
          func: onAuthChange|azure
          paths:
            - temp/properties/azure
      - type: block-layout
        if:
          name: authEnabled
          type: function
        label: Storage Secret
        elements:
        - type: input
          label: Azure Account Name
          forceRequired: true
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/auth/properties/AZURE_ACCOUNT_NAME
        - type: input
          label: Azure Account Key
          forceRequired: true
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/auth/properties/AZURE_ACCOUNT_KEY
    - type: block-layout
      if:
        name: providerType|gcs
        type: function
      elements:
      - type: input
        label: Bucket
        forceRequired: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/spec/properties/bucket
      - type: input
        label: Max Connections
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/spec/properties/maxConnections
      - type: input
        label: Prefix
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/spec/properties/prefix
      - type: switch
        label: Enable Storage Secret?
        init:
          type: func
          value: setStorageSecret
        schema: temp/properties/gcs
        watcher:
          func: onAuthChange|gcs
          paths:
            - temp/properties/gcs
      - type: block-layout
        if:
          name: authEnabled
          type: function
        label: Storage Secret
        elements:
        - type: input
          label: Project ID
          forceRequired: true
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/auth/properties/GOOGLE_PROJECT_ID
        - type: input
          label: Service Account
          forceRequired: true
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/auth/properties/GOOGLE_SERVICE_ACCOUNT_JSON_KEY
    - type: input
      label: Encryption Secret
      customClass: mt-16
      forceRequired: true
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/encryptionSecret
    - type: select
      label: Retention Policy
      options:
      - text: Keep 1 week
        value: keep-1wk
      - text: Keep 1 Month
        value: keep-1mo
      - text: Keep 3 Month
        value: keep-3mo
      - text: Keep 1 Year
        value: keep-1yr
      validation:
        type: required
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/retentionPolicy
    - type: input
      label: Schedule
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/schedule
type: multi-step-form