step:
- elements:
  - individualDisability: disableFeatures
    init:
      type: func
      value: getEnabledFeatures
    label: ""
    loader: fetchFeatureSetOptions
    schema: temp/properties/enabledFeatures
    type: checkbox
    watcher:
      func: onEnabledFeaturesChange
      paths:
      - temp/properties/enabledFeatures
  - customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    type: info
    watcher:
      func: checkIsResourceLoaded
      paths:
      - temp/properties/isResourceLoaded
  - elements:
    - label: Preset Configuration
      type: label-element
    - elements:
      - label: Backend Provider
        options:
        - text: Azure Blob Storage
          value: azure
        - text: Google Cloud Service
          value: gcs
        - text: AWS S3
          value: s3
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/provider
        type: select
      if:
        name: presetType|kubestash
        type: function
      type: block-layout
    - elements:
      - forceRequired: true
        label: Bucket
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/bucket
        type: input
      - forceRequired: true
        label: End Point
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/endpoint
        type: input
      - label: Insecure TLS
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/insecureTLS
        type: input
      - label: Prefix
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/prefix
        type: input
      - label: Region
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/spec/properties/region
        type: input
      - init:
          type: func
          value: setStorageSecret
        label: Enable Storage Secret?
        schema: temp/properties/s3
        type: switch
        watcher:
          func: onAuthChange|s3
          paths:
          - temp/properties/s3
      - elements:
        - forceRequired: true
          label: Access Key ID
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/auth/properties/AWS_ACCESS_KEY_ID
          type: input
        - forceRequired: true
          label: Secret Access Key
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/auth/properties/AWS_SECRET_ACCESS_KEY
          type: input
        - label: CA Cert Data
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/s3/properties/auth/properties/CA_CERT_DATA
          type: input
        if:
          name: authEnabled
          type: function
        label: Storage Secret
        type: block-layout
      if:
        name: providerType|s3
        type: function
      type: block-layout
    - elements:
      - forceRequired: true
        label: Container
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/pro
          perties/azure/properties/spec/properties/container
        type: input
      - label: Max Connections
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/spec/properties/maxConnections
        type: input
      - label: Prefix
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/spec/properties/prefix
        type: input
      - init:
          type: func
          value: setStorageSecret
        label: Enable Storage Secret?
        schema: temp/properties/azure
        type: switch
        watcher:
          func: onAuthChange|azure
          paths:
          - temp/properties/azure
      - elements:
        - forceRequired: true
          label: Azure Account Name
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/auth/properties/AZURE_ACCOUNT_NAME
          type: input
        - forceRequired: true
          label: Azure Account Key
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/azure/properties/auth/properties/AZURE_ACCOUNT_KEY
          type: input
        if:
          name: authEnabled
          type: function
        label: Storage Secret
        type: block-layout
      if:
        name: providerType|azure
        type: function
      type: block-layout
    - elements:
      - forceRequired: true
        label: Bucket
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/spec/properties/bucket
        type: input
      - label: Max Connections
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/spec/properties/maxConnections
        type: input
      - label: Prefix
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/spec/properties/prefix
        type: input
      - init:
          type: func
          value: setStorageSecret
        label: Enable Storage Secret?
        schema: temp/properties/gcs
        type: switch
        watcher:
          func: onAuthChange|gcs
          paths:
          - temp/properties/gcs
      - elements:
        - forceRequired: true
          label: Project ID
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/auth/properties/GOOGLE_PROJECT_ID
          type: input
        - forceRequired: true
          label: Service Account
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/backend/properties/gcs/properties/auth/properties/GOOGLE_SERVICE_ACCOUNT_JSON_KEY
          type: input
        if:
          name: authEnabled
          type: function
        label: Storage Secret
        type: block-layout
      if:
        name: providerType|gcs
        type: function
      type: block-layout
    - customClass: mt-16
      forceRequired: true
      label: Encryption Secret
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/encryptionSecret
      type: input
    - label: Retention Policy
      options:
      - text: Keep 1 week
        value: keep-1wk
      - text: Keep 1 Month
        value: keep-1mo
      - text: Keep 3 Month
        value: keep-3mo
      - text: Keep 1 Year
        value: keep-1yr
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/retentionPolicy
      type: select
      validation:
        type: required
    - label: Schedule
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_stash_presets/properties/spec/properties/values/properties/kubestash/properties/schedule
      type: input
    if:
      name: isStashPreset
      type: function
    type: block-layout
  id: opscenter-backup
  loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
type: multi-step-form
