chart:
  name: catalogappscodecom-aerospikebinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a AerospikeBinding Editor
  description: AerospikeBinding Editor
  name: AerospikeBinding Editor by AppsCode
  shortName: AerospikeBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-aerospikebinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
