chart:
  name: courierkubedbcom-mariadbmigration-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a MariaDBMigration Editor
  description: MariaDBMigration Editor
  name: MariaDBMigration Editor by AppsCode
  shortName: MariaDBMigration Editor
  url: https://appscode.com
release:
  name: courierkubedbcom-mariadbmigration-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
