metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_external_dns_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: external-dns-operator
      name: external-dns-operator
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_gateway_api: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: gateway-api
      name: gateway-api
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_voyager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: voyager
      name: voyager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_voyager_gateway: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: voyager-gateway
      name: voyager-gateway
      namespace: kubeops
