metadata:
  resource:
    group: kubedb.com
    version: v1
    name: redissentinels
    kind: RedisSentinel
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  certManagerIoIssuer_redis_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: redis-ca
      namespace: demo
  gitopsKubedbComRedisSentinel: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: RedisSentinel
    metadata:
      name: redissentinel
      namespace: demo
  kubedbComRedisSentinel: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: RedisSentinel
    metadata:
      name: redissentinel
      namespace: demo
  monitoringCoreosComServiceMonitor_redis: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: redis
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: redissentinel-auth
      namespace: demo
