{{- if or .Values.spec.authSecret.apiKey .Values.spec.authSecret.readOnlyApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubedbcom-qdrant-editor-options.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedbcom-qdrant-editor-options.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.spec.authSecret.apiKey }}
  api-key: {{ . | trim | b64enc | quote }}
  {{- end }}
  {{- with .Values.spec.authSecret.readOnlyApiKey }}
  read-only-api-key: {{ . | trim | b64enc | quote }}
  {{- end }}
{{- end }}
