chart:
  name: kubedbcom-qdrant-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a Qdrant Editor
  description: Qdrant Editor
  name: Qdrant Editor by AppsCode
  shortName: Qdrant Editor
  url: https://appscode.com
release:
  name: kubedbcom-qdrant-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
