form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          qdrantGrpcResponsesFailHigh:
            duration: 5m
            enabled: true
            severity: critical
            val: 5
          qdrantHighCPUUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          qdrantHighMemoryUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          qdrantHighPendingOperations:
            duration: 5m
            enabled: true
            severity: critical
            val: 10
          qdrantInstanceDown:
            duration: 30s
            enabled: true
            severity: critical
          qdrantPhaseCritical:
            duration: 1m
            enabled: true
            severity: warning
          qdrantRestResponsesFailHigh:
            duration: 5m
            enabled: true
            severity: critical
            val: 5
          qdrantRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: prometheus
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: qdrants
    kind: Qdrant
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComQdrantAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: QdrantAutoscaler
    metadata:
      name: qdrant
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: qdrant-ca
      namespace: demo
  kubedbComQdrant: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Qdrant
    metadata:
      name: qdrant
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: qdrant
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: qdrant-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: qdrant-config
      namespace: demo
