form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          qdrantGrpcResponsesFailHigh:
            duration: 5m
            enabled: true
            severity: critical
            val: 5
          qdrantHighCPUUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          qdrantHighMemoryUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          qdrantHighPendingOperations:
            duration: 5m
            enabled: true
            severity: critical
            val: 10
          qdrantInstanceDown:
            duration: 30s
            enabled: true
            severity: critical
          qdrantPhaseCritical:
            duration: 1m
            enabled: true
            severity: warning
          qdrantRestResponsesFailHigh:
            duration: 5m
            enabled: true
            severity: critical
            val: 5
          qdrantRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: prometheus
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: qdrants
    kind: Qdrant
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComQdrantAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: QdrantAutoscaler
    metadata:
      name: qdrant
      namespace: demo
    spec:
      compute:
        nodeTopology:
          name: standard-basv2-family
        qdrant:
          maxAllowed:
            cpu: 1
            memory: 2Gi
          minAllowed:
            cpu: 400m
            memory: 400Mi
          podLifeTimeThreshold: 10m
          resourceDiffPercentage: 20
          trigger: "On"
      databaseRef:
        name: qdrant
      opsRequestOptions:
        apply: IfReady
        timeout: 10m
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: qdrant-ca
      namespace: demo
    spec:
      ca:
        secretName: qdrant-ca
  kubedbComQdrant: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Qdrant
    metadata:
      name: qdrant
      namespace: default
    spec:
      deletionPolicy: WipeOut
      podTemplate:
        spec:
          containers:
            - name: qdrant
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
          nodeSelector:
            app: qdrants.kubedb.com
            instance: hello
            namespace: default
            nodepool: standard-bsv2-family
          podPlacementPolicy:
            name: default
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: qdrants.kubedb.com
            - effect: NoSchedule
              key: instance
              operator: Equal
              value: hello
            - effect: NoSchedule
              key: namespace
              operator: Equal
              value: default
            - effect: NoSchedule
              key: nodepool
              operator: Equal
              value: standard-bsv2-family
      replicas: 3
      serviceTemplates:
        - alias: primary
          spec:
            type: LoadBalancer
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: default
      storageType: Durable
      version: 24.4.1
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: qdrant
      namespace: demo
    spec:
      endpoints:
        - honorLabels: true
          interval: 30s
          path: /metrics
          port: metrics
      namespaceSelector:
        matchNames:
          - demo
      selector:
        matchLabels:
          app.kubernetes.io/instance: qdrant
          app.kubernetes.io/name: qdrants.kubedb.com
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: qdrant-auth
      namespace: demo
    stringData:
      password: thisIs1StrongPassword
      username: root
    type: Opaque
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: qdrant-config
      namespace: demo
    stringData:
      qdrant.cnf: |
        [mysqld]
        max_connections = 200
        read_buffer_size = 1048576
    type: Opaque
