chart:
  name: opskubedbcom-weaviateopsrequest-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a WeaviateOpsRequest Editor
  description: WeaviateOpsRequest Editor
  name: WeaviateOpsRequest Editor by AppsCode
  shortName: WeaviateOpsRequest Editor
  url: https://appscode.com
release:
  name: opskubedbcom-weaviateopsrequest-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
