form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          hanadbHighCPUUsage:
            duration: 5m
            enabled: true
            severity: warning
            val: 80
          hanadbHighMemoryUsage:
            duration: 5m
            enabled: true
            severity: warning
            val: 80
          hanadbInstanceDown:
            duration: 0m
            enabled: true
            severity: critical
          hanadbReplicationNotActive:
            duration: 2m
            enabled: true
            severity: critical
          hanadbRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
          hanadbServiceDown:
            duration: 0m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: hanadbs
    kind: HanaDB
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComHanaDBAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: HanaDBAutoscaler
    metadata:
      name: hanadb
      namespace: demo
    spec:
      compute:
        hanadb:
          maxAllowed:
            cpu: 1
            memory: 2Gi
          minAllowed:
            cpu: 400m
            memory: 400Mi
          podLifeTimeThreshold: 10m
          resourceDiffPercentage: 20
          trigger: "On"
        nodeTopology:
          name: standard-basv2-family
      databaseRef:
        name: hanadb
      opsRequestOptions:
        apply: IfReady
        timeout: 10m
  kubedbComHanaDB: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: HanaDB
    metadata:
      name: hanadb
      namespace: default
    spec:
      deletionPolicy: WipeOut
      podTemplate:
        spec:
          containers:
            - name: hanadb
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
          nodeSelector:
            app: hanadbs.kubedb.com
            instance: hello
            namespace: default
            nodepool: standard-bsv2-family
          podPlacementPolicy:
            name: default
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: hanadbs.kubedb.com
            - effect: NoSchedule
              key: instance
              operator: Equal
              value: hello
            - effect: NoSchedule
              key: namespace
              operator: Equal
              value: default
            - effect: NoSchedule
              key: nodepool
              operator: Equal
              value: standard-bsv2-family
      replicas: 3
      serviceTemplates:
        - alias: primary
          spec:
            type: LoadBalancer
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: default
      storageType: Durable
      version: 24.4.1
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: hanadb
      namespace: demo
    spec:
      endpoints:
        - honorLabels: true
          interval: 30s
          path: /metrics
          port: metrics
      namespaceSelector:
        matchNames:
          - demo
      selector:
        matchLabels:
          app.kubernetes.io/instance: hanadb
          app.kubernetes.io/name: hanadbs.kubedb.com
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: hanadb-auth
      namespace: demo
    stringData:
      password: thisIs1StrongPassword
      username: root
    type: Opaque
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: hanadb-config
      namespace: demo
    stringData:
      hanadb.cnf: |
        [mysqld]
        max_connections = 200
        read_buffer_size = 1048576
    type: Opaque
