form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          hanadbHighCPUUsage:
            duration: 5m
            enabled: true
            severity: warning
            val: 80
          hanadbHighMemoryUsage:
            duration: 5m
            enabled: true
            severity: warning
            val: 80
          hanadbInstanceDown:
            duration: 0m
            enabled: true
            severity: critical
          hanadbReplicationNotActive:
            duration: 2m
            enabled: true
            severity: critical
          hanadbRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
          hanadbServiceDown:
            duration: 0m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: hanadbs
    kind: HanaDB
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComHanaDBAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: HanaDBAutoscaler
    metadata:
      name: hanadb
      namespace: demo
  kubedbComHanaDB: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: HanaDB
    metadata:
      name: hanadb
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: hanadb
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: hanadb-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: hanadb-config
      namespace: demo
