form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          memcachedConnectionThrottled:
            duration: 2m
            enabled: true
            severity: warning
            val: 10
          memcachedConnectionsNoneMinor:
            duration: 2m
            enabled: true
            severity: warning
          memcachedDown:
            duration: 0m
            enabled: true
            severity: critical
          memcachedEvictionsLimit:
            duration: 0m
            enabled: true
            severity: critical
            val: 10
          memcachedItemsNoneMinor:
            duration: 2m
            enabled: true
            severity: warning
          memcachedMemoryLimit:
            duration: 0m
            enabled: true
            severity: critical
            val: 3.3554432e+07
          memcachedServiceRespawn:
            duration: 0m
            enabled: true
            severity: critical
            val: 180
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1
    name: memcacheds
    kind: Memcached
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComMemcachedAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: MemcachedAutoscaler
    metadata:
      name: memcached
      namespace: demo
  catalogAppscodeComMemcachedBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: MemcachedBinding
    metadata:
      name: memcached
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: memcached-ca
      namespace: demo
  gitopsKubedbComMemcached: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: Memcached
    metadata:
      name: memcached
      namespace: sdb
  kubedbComMemcached: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: Memcached
    metadata:
      name: memcached
      namespace: sdb
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: memcached
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: memcached-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: memcached-config
      namespace: demo
