{{- if .Values.spec.configuration }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spec.configurationSecretName | default (printf "%s-config" (include "kubedbcom-milvus-editor-options.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedbcom-milvus-editor-options.labels" . | nindent 4 }}
data:
  milvus.yaml: {{ .Values.spec.configuration | b64enc | quote }}
{{- end }}
