{{- $profiles := dict -}}
{{- with $ctx := . -}}
{{- $profiles = include "resource-profiles" $ctx | fromJson -}}
{{- end -}}

{{- define "common.placement" -}}

{{- if .Values.spec.admin.clusterTier.placement.default }}
podPlacementPolicy:
  name: {{ .Values.spec.admin.clusterTier.placement.default }}
{{- end }}

nodeSelector:
  kubernetes.io/os: linux
{{- if .Values.spec.admin.nodeSelector }}
{{- toYaml .Values.spec.admin.nodeSelector | nindent 2 }}
{{- end }}
{{- if eq .Values.spec.admin.deployment.default "Dedicated" }}
  app: milvuss.kubedb.com
  instance: {{ include "kubedbcom-milvus-editor-options.fullname" . }}
  namespace: {{ .Release.Namespace }}
  nodepool: {{ .Values.spec.admin.clusterTier.nodeTopology.default }}
{{- end }}

{{- if or .Values.spec.admin.tolerations (eq .Values.spec.admin.deployment.default "Dedicated") }}
tolerations:
{{- if .Values.spec.admin.tolerations }}
{{- toYaml .Values.spec.admin.tolerations | nindent 2 }}
{{- end }}
{{- if eq .Values.spec.admin.deployment.default "Dedicated" }}
  - key: app
    operator: "Equal"
    value: "milvuss.kubedb.com"
    effect: "NoSchedule"
  - key: instance
    operator: "Equal"
    value: {{ include "kubedbcom-milvus-editor-options.fullname" . }}
    effect: "NoSchedule"
  - key: namespace
    operator: "Equal"
    value: {{ .Release.Namespace }}
    effect: "NoSchedule"
  - key: nodepool
    operator: "Equal"
    value: {{ .Values.spec.admin.clusterTier.nodeTopology.default }}
    effect: "NoSchedule"
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.spec.admin.gitOps.enable.default }}
apiVersion: gitops.kubedb.com/v1alpha1
{{ else }}
apiVersion: kubedb.com/v1alpha2
{{- end }}
kind: Milvus
metadata:
  name: {{ include "kubedbcom-milvus-editor-options.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedbcom-milvus-editor-options.labels" . | nindent 4 }}
{{- if .Values.spec.admin.archiver.enable.default }}
    kubedb.com/archiver: "true"
    kubedb.com/archiving-via: {{ .Values.spec.admin.archiver.via }}
{{- end }}
  annotations:
    app.kubernetes.io/cluster-tier: {{ .Values.spec.admin.clusterTier.default }}
    {{- if $profiles }}
    kubernetes.io/instance-type: {{ printf "'%s'" (include "resource-profiles" . | fromJson | toJson) }}
    {{- end -}}
  {{- if and (eq .Values.spec.backup.tool "KubeStash") (.Values.spec.admin.backup.enable.default) (eq .Values.spec.admin.backup.by "BackupBlueprint") }}
    blueprint.kubestash.com/name: {{ .Values.metadata.resource.kind | lower }}-blueprint
    blueprint.kubestash.com/namespace: kubedb
  {{- end }}
{{- if .Values.spec.annotations }}
    {{- include "kubedbcom-milvus-editor-options.annotations" . | nindent 4 }}
{{- end }}
spec:
  version: {{ .Values.spec.admin.databases.Milvus.versions.default | quote }}
{{- if .Values.spec.metaStorage }}
  {{- if .Values.spec.metaStorage.externallyManaged }}
    {{- if .Values.spec.metaStorage.endpoints }}
  metaStorage:
    externallyManaged: true
    endpoints:
      {{- toYaml .Values.spec.metaStorage.endpoints | nindent 6 }}
    {{- end }}
  {{- else }}
  metaStorage:
    externallyManaged: false
    size: {{ .Values.spec.metaStorage.size }}
  {{- end }}
{{- end }}
  objectStorage:
    configSecret:
      name: {{ .Values.spec.objectStorage.configSecretName }}
{{- if eq .Values.spec.mode "Distributed" }}
  topology:
    mode: Distributed
    distributed:
      {{- if .Values.spec.distributed.mixcoord }}
      mixcoord:
        replicas: {{ .Values.spec.distributed.mixcoord.replicas }}
        {{- if .Values.spec.distributed.mixcoord.podResources }}
        podTemplate:
          spec:
            containers:
              - name: milvus
                resources:
                  {{- toYaml .mixcoord_res | nindent 18 }}
        {{- end }}
      {{- end }}
      {{- if .Values.spec.distributed.proxy }}
      proxy:
        replicas: {{ .Values.spec.distributed.proxy.replicas }}
        {{- if .Values.spec.distributed.proxy.podResources }}
        podTemplate:
          spec:
            containers:
              - name: milvus
                resources:
                  {{- toYaml .proxy_res | nindent 18 }}
        {{- end }}
      {{- end }}
      {{- if .Values.spec.distributed.streamingnode }}
      streamingnode:
        replicas: {{ .Values.spec.distributed.streamingnode.replicas }}
        storageType: Durable
        storage:
          accessModes:
            - ReadWriteOnce
          storageClassName: {{ .Values.spec.admin.storageClasses.default }}
          resources:
            requests:
              storage: {{ .Values.spec.distributed.streamingnode.persistence.size }}
        {{- if .Values.spec.distributed.streamingnode.podResources }}
        podTemplate:
          spec:
            containers:
              - name: milvus
                resources:
                  {{- toYaml .streamingnode_res | nindent 18 }}
        {{- end }}
      {{- end }}
      {{- if .Values.spec.distributed.datanode }}
      datanode:
        replicas: {{ .Values.spec.distributed.datanode.replicas }}
        {{- if .Values.spec.distributed.datanode.podResources }}
        podTemplate:
          spec:
            containers:
              - name: milvus
                resources:
                  {{- toYaml .datanode_res | nindent 18 }}
        {{- end }}
      {{- end }}
      {{- if .Values.spec.distributed.querynode }}
      querynode:
        replicas: {{ .Values.spec.distributed.querynode.replicas }}
        {{- if .Values.spec.distributed.querynode.podResources }}
        podTemplate:
          spec:
            containers:
              - name: milvus
                resources:
                  {{- toYaml .querynode_res | nindent 18 }}
        {{- end }}
      {{- end }}
{{- else }}
  topology:
    mode: Standalone
{{- end }}
{{- if or (eq .Values.spec.mode "Standalone") .Values.spec.disableSecurity }}
  disableSecurity: {{ .Values.spec.disableSecurity | default false }}
{{- end }}
{{- if ne .Values.spec.mode "Distributed" }}
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.spec.persistence.size }}
    storageClassName: {{ .Values.spec.admin.storageClasses.default }}
{{- end }}
{{- if or .Values.spec.configuration .Values.spec.configurationInline .Values.spec.configurationSecretName }}
  configuration:
    secretName: {{ .Values.spec.configurationSecretName | default (printf "%s-config" (include "kubedbcom-milvus-editor-options.fullname" .)) }}
    {{- if .Values.spec.configurationInline }}
    inline:
      {{- toYaml .Values.spec.configurationInline | nindent 6 }}
    {{- end }}
{{- end }}
{{- if ne .Values.spec.mode "Distributed" }}
  podTemplate:
    spec:
      securityContext:
        fsGroup: {{ .Values.spec.openshift.securityContext.runAsUser | default 54321 }}
      containers:
        - name: milvus
          resources:
            {{- toYaml .res | nindent 12 }}
          securityContext:
            {{- include "container.securityContext" . | nindent 12 }}
      initContainers:
        - name: milvus-init
          resources:
            {{- toYaml .init_res | nindent 12 }}
          securityContext:
            {{- include "container.securityContext" . | nindent 12 }}
      {{- include "common.placement" . | nindent 6 }}
{{- end }}
  deletionPolicy: {{ .Values.spec.deletionPolicy }}
{{- if or .Values.spec.authSecret.name .Values.spec.authSecret.password .Values.spec.authSecret.externallyManaged }}
  authSecret:
    name: {{ .Values.spec.authSecret.name | default (printf "%s-auth" (include "kubedbcom-milvus-editor-options.fullname" .)) }}
    {{- if .Values.spec.authSecret.externallyManaged }}
    externallyManaged: true
    {{- end }}
{{- end }}
{{- if .Values.spec.halted }}
  halted: {{ .Values.spec.halted }}
{{- end }}
