metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_capi_catalog: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: capi-catalog
      name: capi-catalog
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_capi_ops_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: capi-ops-manager
      name: capi-ops-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cluster_presets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-presets
      name: cluster-presets
      namespace: kubeops
