chart:
  name: opskubedbcom-db2opsrequest-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DB2OpsRequest Editor
  description: DB2OpsRequest Editor
  name: DB2OpsRequest Editor by AppsCode
  shortName: DB2OpsRequest Editor
  url: https://appscode.com
release:
  name: opskubedbcom-db2opsrequest-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
