chart:
  name: catalogkubedbcom-documentdbversion-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DocumentDBVersion Editor
  description: DocumentDBVersion Editor
  name: DocumentDBVersion Editor by AppsCode
  shortName: DocumentDBVersion Editor
  url: https://appscode.com
release:
  name: catalogkubedbcom-documentdbversion-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
