step:
- elements:
  - individualDisability: disableFeatures
    init:
      type: func
      value: getEnabledFeatures
    label: ""
    loader: fetchFeatureSetOptions
    schema: temp/properties/enabledFeatures
    type: checkbox
    watcher:
      func: onEnabledFeaturesChange
      paths:
      - temp/properties/enabledFeatures
  - customClass: mt-16
    if:
      name: isKubedbSelected
      type: function
    init:
      type: func
      value: getEnabledTypes
    label: Select Database Types
    loader: getDatabaseTypes
    multiple: true
    schema: temp/properties/enabledTypes
    type: select
    watcher:
      func: onTypeUpdate
      paths:
      - temp/properties/enabledTypes
  - label: 'Note: Enabling a feature auto enables any prerequisite features'
    type: info
    watcher:
      func: checkIsResourceLoaded
      paths:
      - temp/properties/isResourceLoaded
  id: opscenter-datastore
  loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
type: multi-step-form
