step:
- elements:
  - elements:
    - individualDisability: disableFeatures
      init:
        type: func
        value: getEnabledFeatures
      label: ""
      loader: fetchFeatureSetOptions
      schema: temp/properties/enabledFeatures
      type: checkbox
      watcher:
        func: onEnabledFeaturesChange
        paths:
        - temp/properties/enabledFeatures
    - label: 'Note: Enabling a feature auto enables any prerequisite features'
      type: info
      watcher:
        func: checkIsResourceLoaded
        paths:
        - temp/properties/isResourceLoaded
    - customClass: mt-16
      if:
        name: isKubedbSelected
        type: function
      init:
        type: func
        value: getEnabledTypes
      label: Select Database Types
      loader: getDatabaseTypes
      multiple: true
      schema: temp/properties/enabledTypes
      type: select
      watcher:
        func: onTypeUpdate
        paths:
        - temp/properties/enabledTypes
    if:
      name: showForm|configure
      type: function
    type: block-layout
  - elements:
    - elements:
      - if:
          name: isDbSelected|Cassandra
          type: function
        init:
          type: func
          value: setVersions|Cassandra
        label: Cassandra Versions
        loader: getVersions|Cassandra
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Cassandra
        type: select
      loader: getVersions|Cassandra
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|ClickHouse
          type: function
        init:
          type: func
          value: setVersions|ClickHouse
        label: ClickHouse Versions
        loader: getVersions|ClickHouse
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/ClickHouse
        type: select
      loader: getVersions|ClickHouse
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|DB2
          type: function
        init:
          type: func
          value: setVersions|DB2
        label: DB2 Versions
        loader: getVersions|DB2
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/DB2
        type: select
      loader: getVersions|DB2
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|DocumentDB
          type: function
        init:
          type: func
          value: setVersions|DocumentDB
        label: DocumentDB Versions
        loader: getVersions|DocumentDB
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/DocumentDB
        type: select
      loader: getVersions|DocumentDB
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Druid
          type: function
        init:
          type: func
          value: setVersions|Druid
        label: Druid Versions
        loader: getVersions|Druid
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Druid
        type: select
      loader: getVersions|Druid
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Elasticsearch
          type: function
        init:
          type: func
          value: setVersions|Elasticsearch
        label: Elasticsearch Versions
        loader: getVersions|Elasticsearch
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Elasticsearch
        type: select
      loader: getVersions|Elasticsearch
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|HanaDB
          type: function
        init:
          type: func
          value: setVersions|HanaDB
        label: HanaDB Versions
        loader: getVersions|HanaDB
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/HanaDB
        type: select
      loader: getVersions|HanaDB
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Hazelcast
          type: function
        init:
          type: func
          value: setVersions|Hazelcast
        label: Hazelcast Versions
        loader: getVersions|Hazelcast
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Hazelcast
        type: select
      loader: getVersions|Hazelcast
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Ignite
          type: function
        init:
          type: func
          value: setVersions|Ignite
        label: Ignite Versions
        loader: getVersions|Ignite
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Ignite
        type: select
      loader: getVersions|Ignite
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Kafka
          type: function
        init:
          type: func
          value: setVersions|Kafka
        label: Kafka Versions
        loader: getVersions|Kafka
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Kafka
        type: select
      loader: getVersions|Kafka
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|MariaDB
          type: function
        init:
          type: func
          value: setVersions|MariaDB
        label: MariaDB Versions
        loader: getVersions|MariaDB
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/MariaDB
        type: select
      loader: getVersions|MariaDB
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Memcached
          type: function
        init:
          type: func
          value: setVersions|Memcached
        label: Memcached Versions
        loader: getVersions|Memcached
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Memcached
        type: select
      loader: getVersions|Memcached
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Milvus
          type: function
        init:
          type: func
          value: setVersions|Milvus
        label: Milvus Versions
        loader: getVersions|Milvus
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Milvus
        type: select
      loader: getVersions|Milvus
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|MSSQLServer
          type: function
        init:
          type: func
          value: setVersions|MSSQLServer
        label: MSSQLServer Versions
        loader: getVersions|MSSQLServer
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/MSSQLServer
        type: select
      loader: getVersions|MSSQLServer
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|MongoDB
          type: function
        init:
          type: func
          value: setVersions|MongoDB
        label: MongoDB Versions
        loader: getVersions|MongoDB
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/MongoDB
        type: select
      loader: getVersions|MongoDB
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|MySQL
          type: function
        init:
          type: func
          value: setVersions|MySQL
        label: MySQL Versions
        loader: getVersions|MySQL
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/MySQL
        type: select
      loader: getVersions|MySQL
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Neo4j
          type: function
        init:
          type: func
          value: setVersions|Neo4j
        label: Neo4j Versions
        loader: getVersions|Neo4j
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Neo4j
        type: select
      loader: getVersions|Neo4j
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Oracle
          type: function
        init:
          type: func
          value: setVersions|Oracle
        label: Oracle Versions
        loader: getVersions|Oracle
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Oracle
        type: select
      loader: getVersions|Oracle
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|PerconaXtraDB
          type: function
        init:
          type: func
          value: setVersions|PerconaXtraDB
        label: PerconaXtraDB Versions
        loader: getVersions|PerconaXtraDB
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/PerconaXtraDB
        type: select
      loader: getVersions|PerconaXtraDB
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|PgBouncer
          type: function
        init:
          type: func
          value: setVersions|PgBouncer
        label: PgBouncer Versions
        loader: getVersions|PgBouncer
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/PgBouncer
        type: select
      loader: getVersions|PgBouncer
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Pgpool
          type: function
        init:
          type: func
          value: setVersions|Pgpool
        label: Pgpool Versions
        loader: getVersions|Pgpool
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Pgpool
        type: select
      loader: getVersions|Pgpool
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Postgres
          type: function
        init:
          type: func
          value: setVersions|Postgres
        label: Postgres Versions
        loader: getVersions|Postgres
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Postgres
        type: select
      loader: getVersions|Postgres
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|ProxySQL
          type: function
        init:
          type: func
          value: setVersions|ProxySQL
        label: ProxySQL Versions
        loader: getVersions|ProxySQL
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/ProxySQL
        type: select
      loader: getVersions|ProxySQL
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Qdrant
          type: function
        init:
          type: func
          value: setVersions|Qdrant
        label: Qdrant Versions
        loader: getVersions|Qdrant
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Qdrant
        type: select
      loader: getVersions|Qdrant
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|RabbitMQ
          type: function
        init:
          type: func
          value: setVersions|RabbitMQ
        label: RabbitMQ Versions
        loader: getVersions|RabbitMQ
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/RabbitMQ
        type: select
      loader: getVersions|RabbitMQ
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Redis
          type: function
        init:
          type: func
          value: setVersions|Redis
        label: Redis Versions
        loader: getVersions|Redis
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Redis
        type: select
      loader: getVersions|Redis
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Singlestore
          type: function
        init:
          type: func
          value: setVersions|Singlestore
        label: Singlestore Versions
        loader: getVersions|Singlestore
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Singlestore
        type: select
      loader: getVersions|Singlestore
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Solr
          type: function
        init:
          type: func
          value: setVersions|Solr
        label: Solr Versions
        loader: getVersions|Solr
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Solr
        type: select
      loader: getVersions|Solr
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|Weaviate
          type: function
        init:
          type: func
          value: setVersions|Weaviate
        label: Weaviate Versions
        loader: getVersions|Weaviate
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/Weaviate
        type: select
      loader: getVersions|Weaviate
      type: block-layout
    - elements:
      - if:
          name: isDbSelected|ZooKeeper
          type: function
        init:
          type: func
          value: setVersions|ZooKeeper
        label: ZooKeeper Versions
        loader: getVersions|ZooKeeper
        multiple: true
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_kubedb/properties/spec/properties/values/properties/kubedb-catalog/properties/enableVersions/properties/ZooKeeper
        type: select
      loader: getVersions|ZooKeeper
      type: block-layout
    if:
      name: showForm|versions
      type: function
    type: block-layout
  id: opscenter-datastore
  loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
type: multi-step-form
