chart:
  name: catalogappscodecom-weaviatebinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a WeaviateBinding Editor
  description: WeaviateBinding Editor
  name: WeaviateBinding Editor by AppsCode
  shortName: WeaviateBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-weaviatebinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
