step:
- loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
  id: opscenter-security
  elements:
  - type: checkbox
    schema: temp/properties/enabledFeatures
    label: ''
    loader: fetchFeatureSetOptions
    init:
      type: func
      value: getEnabledFeatures
    watcher:
      func: onEnabledFeaturesChange
      paths:
        - temp/properties/enabledFeatures
  - type: info
    customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    watcher:
      func: checkIsResourceLoaded
      paths:
        - temp/properties/isResourceLoaded
    # options:
    #   - text: Cert Manager
    #     value: cert-manager
    #     description: X.509 certificate management for Kubernetes and OpenShift
    #   - text: CA Cert CSI Driver
    #     value: ca-cert-csi-driver
    #     description: CSI Driver to mount ca-certs issued by cert-manager
    #   - text: Falco
    #     value: falco
    #     description: Container Native Runtime Security
    #   - text: Falco UI Server
    #     value: falco-ui-server
    #     description: Falco UI Server
    #   - text: Scanner
    #     value: scanner
    #     description: Scan docker image vulnerability and generate security report.
  
type: multi-step-form
