form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          solrDownShards:
            duration: 30s
            enabled: true
            severity: critical
            val: 0
          solrHighBufferSize:
            duration: 30s
            enabled: true
            severity: warning
            val: 3e+06
          solrHighHeapSize:
            duration: 30s
            enabled: true
            severity: warning
            val: 3e+06
          solrHighPoolSize:
            duration: 30s
            enabled: true
            severity: warning
            val: 3e+06
          solrHighQPS:
            duration: 30s
            enabled: true
            severity: warning
            val: 1000
          solrHighThreadRunning:
            duration: 30s
            enabled: true
            severity: warning
            val: 300
          solrRecoveryFailedShards:
            duration: 30s
            enabled: true
            severity: critical
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 1m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: solrs
    kind: Solr
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComSolrAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: SolrAutoscaler
    metadata:
      name: solr
      namespace: demo
  catalogAppscodeComSolrBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: SolrBinding
    metadata:
      name: solr
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: solr-ca
      namespace: demo
  gitopsKubedbComSolr: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: Solr
    metadata:
      name: solr
      namespace: solr
  kubedbComSolr: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Solr
    metadata:
      name: solr
      namespace: solr
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: solr
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: solr-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: solr-config
      namespace: demo
