metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: aerospikes
    kind: Aerospike
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComAerospikeAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: AerospikeAutoscaler
    metadata:
      name: aerospike
      namespace: demo
    spec:
      compute:
        aerospike:
          maxAllowed:
            cpu: 1
            memory: 2Gi
          minAllowed:
            cpu: 400m
            memory: 400Mi
          podLifeTimeThreshold: 10m
          resourceDiffPercentage: 20
          trigger: "On"
        nodeTopology:
          name: standard-basv2-family
      databaseRef:
        name: aerospike
      opsRequestOptions:
        apply: IfReady
        timeout: 10m
  kubedbComAerospike: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Aerospike
    metadata:
      name: aerospike
      namespace: demo
    spec:
      authSecret:
        name: aerospike-auth
      cluster:
        replicas: 3
        replicationFactor: 2
      deletionPolicy: WipeOut
      mode: Cluster
      version: 7.2.0.7
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: aerospike-auth
      namespace: demo
    stringData:
      password: thisIs1StrongPassword
      username: root
    type: Opaque
