metadata:
  resource:
    group: core.kubestash.com
    version: v1alpha1
    name: restoresessions
    kind: RestoreSession
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: restore-app
      namespace: demo
