metadata:
  resource:
    group: core.kubestash.com
    version: v1alpha1
    name: backupconfigurations
    kind: BackupConfiguration
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: backup-app
      namespace: demo
