annotations:
  meta.x-helm.dev/editor: '{"group":"catalog.appscode.com","version":"v1alpha1","resource":"ignitebindings"}'
apiVersion: v2
appVersion: v0.35.0
description: IgniteBinding Editor
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- appscode
kubeVersion: '>= 1.20.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: catalogappscodecom-ignitebinding-editor
type: application
version: v0.35.0
