chart:
  name: gatewayvoyagermeshcom-oracleroute-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a OracleRoute Editor
  description: OracleRoute Editor
  name: OracleRoute Editor by AppsCode
  shortName: OracleRoute Editor
  url: https://appscode.com
release:
  name: gatewayvoyagermeshcom-oracleroute-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
