step:
- elements:
  - individualDisability: disableFeatures
    init:
      type: func
      value: getEnabledFeatures
    label: ""
    loader: fetchFeatureSetOptions
    schema: temp/properties/enabledFeatures
    type: checkbox
    watcher:
      func: onEnabledFeaturesChange
      paths:
      - temp/properties/enabledFeatures
  - customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    type: info
    watcher:
      func: checkIsResourceLoaded
      paths:
      - temp/properties/isResourceLoaded
  - if:
      name: checkIsOtelStackEnabled
      type: function
    label: Select Monitoring Cluster
    loader: fetchMonitoringClusterOptions
    schema: temp/properties/monitoringClusterName
    type: select
    validation:
      type: required
    watcher:
      func: onMonitoringClusterChange
      paths:
      - temp/properties/monitoringClusterName
  id: opscenter-monitoring
  loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
type: multi-step-form
