chart:
  name: catalogappscodecom-milvusbinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a MilvusBinding Editor
  description: MilvusBinding Editor
  name: MilvusBinding Editor by AppsCode
  shortName: MilvusBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-milvusbinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
