apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectors.kafka.kubedb.com
spec:
  group: kafka.kubedb.com
  names:
    kind: Connector
    listKind: ConnectorList
    plural: connectors
    singular: connector
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              configSecret:
                properties:
                  name:
                    default: ""
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              configuration:
                properties:
                  inline:
                    additionalProperties:
                      type: string
                    type: object
                  secretName:
                    type: string
                type: object
              connectClusterRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
              deletionPolicy:
                enum:
                - Halt
                - Delete
                - WipeOut
                - DoNotTerminate
                type: string
            required:
            - configuration
            - connectClusterRef
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
