chart:
  name: catalogappscodecom-documentdbbinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DocumentDBBinding Editor
  description: DocumentDBBinding Editor
  name: DocumentDBBinding Editor by AppsCode
  shortName: DocumentDBBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-documentdbbinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
