form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteClusterNoBaselineNode:
            duration: 1m
            enabled: true
            severity: warning
            val: 0
          igniteDown:
            duration: 30s
            enabled: true
            severity: critical
          igniteHighCPULoad:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteHighDataregionOffHeapUsed:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteHighHeapMemoryUsed:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteJVMPausesTotalDuration:
            duration: 1m
            enabled: true
            severity: warning
            val: 0
          ignitePhaseCritical:
            duration: 1m
            enabled: true
            severity: warning
          igniteRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: ignites
    kind: Ignite
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComIgniteAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: IgniteAutoscaler
    metadata:
      name: ignite
      namespace: demo
    spec:
      compute:
        ignite:
          maxAllowed:
            cpu: 1
            memory: 2Gi
          minAllowed:
            cpu: 400m
            memory: 400Mi
          podLifeTimeThreshold: 10m
          resourceDiffPercentage: 20
          trigger: "On"
        nodeTopology:
          name: standard-basv2-family
      databaseRef:
        name: ignite
      opsRequestOptions:
        apply: IfReady
        timeout: 10m
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: ignite-ca
      namespace: demo
    spec:
      ca:
        secretName: ignite-ca
  kubedbComIgnite: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Ignite
    metadata:
      name: ignite
      namespace: ignite
    spec:
      deletionPolicy: Halt
      podTemplate:
        spec:
          containers:
            - name: ignite
              resources:
                requests:
                  cpu: 700m
                  memory: 1200Mi
          nodeSelector:
            app: kubedb
            component: ignite-database
            instance: ignite
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: kubedb
            - effect: NoSchedule
              key: instance
              operator: Equal
              value: ignite
            - effect: NoSchedule
              key: component
              operator: Equal
              value: ignite-database
            - effect: NoSchedule
              key: nodepool_type
              operator: Equal
              value: n2-standard-2
      replicas: 3
      serviceTemplates:
        - alias: primary
          spec:
            type: LoadBalancer
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      version: 3.8.3
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: ignite
      namespace: demo
    spec:
      endpoints:
        - honorLabels: true
          interval: 30s
          path: /metrics
          port: metrics
      namespaceSelector:
        matchNames:
          - demo
      selector:
        matchLabels:
          app.kubernetes.io/instance: ignite
          app.kubernetes.io/name: ignites.kubedb.com
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: ignite-auth
      namespace: demo
    stringData:
      password: thisIs1StrongPassword
      username: root
    type: Opaque
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: ignite-config
      namespace: demo
    stringData:
      ignite.cnf: |
        [mysqld]
        max_connections = 200
        read_buffer_size = 1048576
    type: Opaque
