form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteClusterNoBaselineNode:
            duration: 1m
            enabled: true
            severity: warning
            val: 0
          igniteDown:
            duration: 30s
            enabled: true
            severity: critical
          igniteHighCPULoad:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteHighDataregionOffHeapUsed:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteHighHeapMemoryUsed:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          igniteJVMPausesTotalDuration:
            duration: 1m
            enabled: true
            severity: warning
            val: 0
          ignitePhaseCritical:
            duration: 1m
            enabled: true
            severity: warning
          igniteRestarted:
            duration: 1m
            enabled: true
            severity: warning
            val: 180
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: ignites
    kind: Ignite
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComIgniteAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: IgniteAutoscaler
    metadata:
      name: ignite
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: ignite-ca
      namespace: demo
  kubedbComIgnite: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Ignite
    metadata:
      name: ignite
      namespace: ignite
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: ignite
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: ignite-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: ignite-config
      namespace: demo
