form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          hazelcastDown:
            duration: 30s
            enabled: true
            severity: critical
          hazelcastHighHeapPercentage:
            duration: 30s
            enabled: true
            severity: warning
            val: 80
          hazelcastHighLatency:
            duration: 30s
            enabled: true
            severity: warning
            val: 2.5
          hazelcastHighMemoryUsage:
            duration: 30s
            enabled: true
            severity: warning
            val: 80
          hazelcastHighPhysicalMemoryUsage:
            duration: 30s
            enabled: true
            severity: warning
            val: 50
          hazelcastPartitionCountExceed:
            duration: 30s
            enabled: true
            severity: warning
            val: 92
          hazelcastPhaseCritical:
            duration: 3m
            enabled: true
            severity: warning
          hazelcastSystemCPULoadExceed:
            duration: 30s
            enabled: true
            severity: warning
            val: 5
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: hazelcasts
    kind: Hazelcast
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComHazelcastAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: HazelcastAutoscaler
    metadata:
      name: hazelcast
      namespace: demo
  catalogAppscodeComHazelcastBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: HazelcastBinding
    metadata:
      name: hazelcast
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: hazelcast-ca
      namespace: demo
  kubedbComHazelcast: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Hazelcast
    metadata:
      name: hazelcast
      namespace: hazelcast
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: hazelcast
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: hazelcast-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: hazelcast-config
      namespace: demo
