chart:
  name: gatewaynetworkingxk8sio-xlistenerset-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a XListenerSet Editor
  description: XListenerSet Editor
  name: XListenerSet Editor by AppsCode
  shortName: XListenerSet Editor
  url: https://appscode.com
release:
  name: gatewaynetworkingxk8sio-xlistenerset-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
