chart:
  name: kubedbcom-neo4j-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a Neo4j Editor
  description: Neo4j Editor
  name: Neo4j Editor by AppsCode
  shortName: Neo4j Editor
  url: https://appscode.com
release:
  name: kubedbcom-neo4j-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
