form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          neo4jHighCPUUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          neo4jHighMemoryUsage:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          neo4jPageCacheHitRatioLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 0.98
          neo4jPageCacheUsageRatioHigh:
            duration: 5m
            enabled: true
            severity: warning
            val: 0.85
          neo4jPageFaultFailuresHigh:
            duration: 5m
            enabled: true
            severity: critical
            val: 0
          neo4jPageFaultsHigh:
            duration: 5m
            enabled: true
            severity: warning
            val: 5000
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: prometheus
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: neo4js
    kind: Neo4j
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComNeo4jAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: Neo4jAutoscaler
    metadata:
      name: neo4j
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: neo4j-ca
      namespace: demo
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: neo4j
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: neo4j
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: neo4j
      namespace: demo
  kubedbComNeo4j: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Neo4j
    metadata:
      name: neo4j
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: neo4j
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: neo4j-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: neo4j-config
      namespace: demo
