metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_catalog_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: catalog-manager
      name: catalog-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_service_backend: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: service-backend
      name: service-backend
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_service_gateway_presets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: service-gateway-presets
      name: service-gateway-presets
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_service_provider: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: service-provider
      name: service-provider
      namespace: kubeops
