step:
- elements:
  - individualDisability: disableFeatures
    init:
      type: func
      value: getEnabledFeatures
    label: ""
    loader: fetchFeatureSetOptions
    schema: temp/properties/enabledFeatures
    type: checkbox
    watcher:
      func: onEnabledFeaturesChange
      paths:
      - temp/properties/enabledFeatures
  - customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    type: info
    watcher:
      func: checkIsResourceLoaded
      paths:
      - temp/properties/isResourceLoaded
  - elements:
    - elements:
      - label: caCert
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/cluster/properties/tls/properties/ca/properties/cert
        type: textarea
      - label: caKey
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/cluster/properties/tls/properties/ca/properties/key
        type: textarea
      hideBlock: true
      label: Cluster
      showLabels: true
      type: block-layout
    - elements:
      - label: Nodeport Range
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/envoy/properties/service/properties/nodeportRange
        type: input
      - label: Port Range
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/envoy/properties/service/properties/portRange
        type: input
      - element:
          label: External IP
          type: input
        label: External IPs
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/envoy/properties/service/properties/externalIPs
        type: array-item-form
      - elements:
        - label: External Traffic Policy
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/envoy/properties/service/properties/externalTrafficPolicy
          type: select
        - label: type
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/envoy/properties/service/properties/type
          type: select
        label: Envoy Service Ports
        showLabels: true
        type: block-layout
      - label: Enable Gateway Converter?
        schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/gateway/properties/gateway-converter/properties/enabled
        type: switch
      - elements:
        - label: Name
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/vaultServer/properties/name
          type: input
        - label: Namespace
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/vaultServer/properties/namespace
          type: input
        label: Vault Server
        showLabels: true
        type: block-layout
      - elements:
        - elements:
          - label: provider
            schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/provider
            type: select
          - elements:
            - forceRequired: true
              label: Environment
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/environment
              type: input
            - forceRequired: true
              label: Hosted Zone Name
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/hostedZoneName
              type: input
            - forceRequired: true
              label: Resource Group Name
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/resourceGroupName
              type: input
            - forceRequired: true
              label: Service Principal App ID
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/servicePrincipalAppID
              type: input
            - forceRequired: true
              label: Service Principal App Password
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/servicePrincipalAppPassword
              type: input
            - forceRequired: true
              label: Subscription ID
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/subscriptionID
              type: input
            - forceRequired: true
              label: Tenant ID
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/azureDNS/properties/tenantID
              type: input
            if:
              name: checkDnsProvider|azureDNS
              type: function
            label: Azure DNS
            showLabels: true
            type: block-layout
          - elements:
            - forceRequired: true
              label: GOOGLE PROJECT ID
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/cloudDNS/properties/GOOGLE_PROJECT_ID
              type: input
            - forceRequired: true
              label: GOOGLE SERVICE ACCOUNT KEY (JSON)
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/cloudDNS/properties/GOOGLE_SERVICE_ACCOUNT_JSON_KEY
              type: input
            if:
              name: checkDnsProvider|cloudDNS
              type: function
            label: cloudDNS
            showLabels: true
            type: block-layout
          - elements:
            - forceRequired: true
              label: Base URL
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/cloudflare/properties/baseURL
              type: input
            - forceRequired: true
              label: Token
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/cloudflare/properties/token
              type: input
            if:
              name: checkDnsProvider|cloudflare
              type: function
            label: cloudflare
            showLabels: true
            type: block-layout
          - elements:
            - forceRequired: true
              label: AWS Access Key ID
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/route53/properties/AWS_ACCESS_KEY_ID
              type: input
            - forceRequired: true
              label: AWS Region
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/route53/properties/AWS_REGION
              type: input
            - forceRequired: true
              label: AWS Secret Access Key
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/dns/properties/auth/properties/route53/properties/AWS_SECRET_ACCESS_KEY
              type: input
            if:
              name: checkDnsProvider|route53
              type: function
            label: route53
            showLabels: true
            type: block-layout
          label: DNS
          showLabels: true
          type: block-layout
        - label: Host
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/host
          type: input
        - label: Host Type
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/hostType
          type: select
        - elements:
          - label: Issuer
            schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/issuer
            type: select
          - elements:
            - forceRequired: true
              label: Email
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/acme/properties/email
              type: input
            - label: Solver
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/acme/properties/solver
              type: select
              validation:
                type: required
            if:
              name: checkIssuer|letsencrypt
              type: function
            label: acme
            showLabels: true
            type: block-layout
          - elements:
            - label: caCert
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/ca/properties/cert
              type: textarea
              validation:
                type: required
            - label: caKey
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/ca/properties/key
              type: textarea
              validation:
                type: required
            if:
              name: checkIssuer|ca
              type: function
            label: ca
            showLabels: true
            type: block-layout
          - elements:
            - label: Certificate Cert
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/certificate/properties/cert
              type: textarea
              validation:
                type: required
            - label: Certificate Key
              schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/infra/properties/tls/properties/certificate/properties/key
              type: textarea
              validation:
                type: required
            if:
              name: checkIssuer|external
              type: function
            label: certificate
            showLabels: true
            type: block-layout
          label: TLS
          showLabels: true
          type: block-layout
        - label: Skip creating GatewayPreset?
          schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_service_gateway_presets/properties/spec/properties/values/properties/skipGatewayPreset
          type: switch
        label: Infra
        showLabels: true
        type: block-layout
      showLabels: false
      type: block-layout
    if:
      name: isServiceGatewaySelected
      type: function
    type: block-layout
  id: saas-core
  loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
type: multi-step-form
