bn: {}
en:
  labels:
    agent: Select a Monitoring Method
    milvus: Milvus
    node_selection_policy: Node Selection Policy
    topology: Topology
    alias: Alias
    annotations:
      key: Key
      label: Annotations
      value: Value
    api_group: API Group
    apply: Apply
    args: Args
    basic_info: Basic Information
    certificate: Certificate
    certificates: Certificates
    config_ops_request: Configure Ops Request
    configuration: Configuration
    configSecret: Config Secret
    createConfig: Create Secret
    applyConfig:
      key: Key
      value: Value
      label: Apply Config
    countries: Countries
    country: Country
    cpu: CPU
    database:
      mode: Database Mode
      name: Milvus Name
      secret: Database Secret
      version: Database Version
    databaseRef: Select your database
    dns_name: DNS Name
    dns_names: DNS Names
    duration: Duration
    enable_tls: Enable TLS
    issuer_ref: Issuer Reference
    key: Key
    kind: Kind
    labels:
      key: Key
      label: Labels
      value: Value
    memory: Memory
    name: Name
    namespace: Namespace
    new_secret_password: New Database Secret
    node: Node
    op_req_name: Ops Request Name
    ops_request_type: Type of Ops Request
    organization: Organization
    organizational_unit: Organizational Unit
    organizational_units: Organizational Units
    organizations: Organizations
    province: Province
    provinces: Provinces
    reconfigurationType: Reconfiguration Type
    removeCustomConfig: Remove Custom Config?
    renew_before: Renew Before
    replicas: Replicas
    resources: Resources
    secret: Secret
    secret_name: Secret Name
    storage:
      class: Storage Class
      size: Storage Size
    subject: Subject
    targetVersion: Select Target Version
    timeout: Timeout
    tls: Reconfigure TLS
    tlsOperation: Choose TLS Operation
    type: Type
    value: Value
  options:
    HorizontalScaling:
      description: Scale up or down pod count
      text: Horizontal Scaling
    Reconfigure:
      description: Reconfigure your database
      text: Reconfigure
    ReconfigureTLS:
      description: Reconfigure your database tls configuration
      text: Reconfigure TLS
    Restart:
      description: Restart your database
      text: Restart
    UpdateVersion:
      description: Update your database to any version
      text: Update Version
    VerticalScaling:
      description: Manage your CPU resources
      text: Vertical Scaling
    VolumeExpansion:
      description: Manage your database size
      text: Volume Expansion
    RotateAuth:
      description: Rotate authentication credentials
      text: Rotate Auth
    StorageMigration:
      description: Migrate storage
      text: Storage Migration
  steps:
    - label: Basic Information
