form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          rabbitmqDown:
            duration: 30s
            enabled: true
            severity: critical
          rabbitmqFileDescriptorsNearLimit:
            duration: 30s
            enabled: true
            severity: warning
          rabbitmqHighConnectionChurn:
            duration: 30s
            enabled: true
            severity: warning
          rabbitmqInsufficientEstablishedErlangDistributionLinks:
            duration: 30s
            enabled: true
            severity: warning
          rabbitmqLowDiskWatermarkPredicted:
            duration: 30s
            enabled: true
            severity: warning
          rabbitmqPhaseCritical:
            duration: 3m
            enabled: true
            severity: warning
          rabbitmqQueueIsGrowing:
            duration: 30s
            enabled: true
            severity: warning
          rabbitmqTCPSocketsNearLimit:
            duration: 30s
            enabled: true
            severity: warning
          rabbitmqUnroutableMessages:
            duration: 30s
            enabled: true
            severity: warning
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: rabbitmqs
    kind: RabbitMQ
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComRabbitMQAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: RabbitMQAutoscaler
    metadata:
      name: rabbitmq
      namespace: demo
  catalogAppscodeComRabbitMQBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: RabbitMQBinding
    metadata:
      name: rabbitmq
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: rabbitmq-ca
      namespace: demo
  gitopsKubedbComRabbitMQ: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: RabbitMQ
    metadata:
      name: rabbitmq
      namespace: sdb
  kubedbComRabbitMQ: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: RabbitMQ
    metadata:
      name: rabbitmq
      namespace: sdb
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: rabbitmq
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: rabbitmq-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: rabbitmq-config
      namespace: demo
