metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_kubestash: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubestash
      name: kubestash
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_stash: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: stash
      name: stash
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_stash_opscenter: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: stash-opscenter
      name: stash-opscenter
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_stash_presets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: stash-presets
      name: stash-presets
      namespace: kubeops
