form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          zookeeperDown:
            duration: 1m
            enabled: true
            severity: critical
          zookeeperJvmMemoryFilingUp:
            duration: 1m
            enabled: true
            severity: warning
            val: 0.8
          zookeeperLeaderElection:
            duration: 1m
            enabled: true
            severity: warning
          zookeeperTooBigMemory:
            duration: 1m
            enabled: true
            severity: warning
            val: 1
          zookeeperTooHighAvgLatency:
            duration: 1m
            enabled: true
            severity: warning
            val: 100
          zookeeperTooLongFsyncTime:
            duration: 1m
            enabled: true
            severity: warning
            val: 100
          zookeeperTooLongSnapshotTime:
            duration: 1m
            enabled: true
            severity: warning
            val: 100
          zookeeperTooManyConnections:
            duration: 1m
            enabled: true
            severity: warning
            val: 60
          zookeeperTooManyNodes:
            duration: 1m
            enabled: true
            severity: warning
            val: 1e+06
          zookeeperTooManyOpenFiles:
            duration: 1m
            enabled: true
            severity: warning
            val: 300
          zookeeperTooManyWatch:
            duration: 1m
            enabled: true
            severity: warning
            val: 10000
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: zookeepers
    kind: ZooKeeper
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComZooKeeperAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: ZooKeeperAutoscaler
    metadata:
      name: zookeeper
      namespace: demo
  catalogAppscodeComZooKeeperBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: ZooKeeperBinding
    metadata:
      name: zookeeper
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: zookeeper-ca
      namespace: demo
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: zookeeper
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: zookeeper
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: zookeeper
      namespace: demo
  kubedbComZooKeeper: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: ZooKeeper
    metadata:
      name: zookeeper
      namespace: zookeeper
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: zookeeper
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: zookeeper-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: zookeeper-config
      namespace: demo
