metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_keda: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: keda
      name: keda
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_keda_add_ons_http: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: keda-add-ons-http
      name: keda-add-ons-http
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_opencost: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: opencost
      name: opencost
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_opencost_grafana_dashboards: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: opencost-grafana-dashboards
      name: opencost-grafana-dashboards
      namespace: kubeops
