metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_cert_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cert-manager
      name: cert-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cert_manager_csi_driver_cacerts: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cert-manager-csi-driver-cacerts
      name: cert-manager-csi-driver-cacerts
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_falco: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: falco
      name: falco
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_falco_ui_server: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: falco-ui-server
      name: falco-ui-server
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_scanner: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: scanner
      name: scanner
      namespace: kubeops
