chart:
  name: courierkubedbcom-mongodbmigration-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a MongoDBMigration Editor
  description: MongoDBMigration Editor
  name: MongoDBMigration Editor by AppsCode
  shortName: MongoDBMigration Editor
  url: https://appscode.com
release:
  name: courierkubedbcom-mongodbmigration-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
