metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_kubedb: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubedb
      name: kubedb
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kubedb_opscenter: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubedb-opscenter
      name: kubedb-opscenter
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kubedb_ui_presets: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kubedb-ui-presets
      name: kubedb-ui-presets
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_prepare_cluster: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: prepare-cluster
      name: prepare-cluster
      namespace: kubeops
