metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_aceshifter: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: aceshifter
      name: aceshifter
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_flux2: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: flux2
      name: flux2
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kube_ui_server: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kube-ui-server
      name: kube-ui-server
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_license_proxyserver: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: license-proxyserver
      name: license-proxyserver
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_opscenter_features: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: opscenter-features
      name: opscenter-features
      namespace: kubeops
