chart:
  name: catalogkubedbcom-milvusversion-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a MilvusVersion Editor
  description: MilvusVersion Editor
  name: MilvusVersion Editor by AppsCode
  shortName: MilvusVersion Editor
  url: https://appscode.com
release:
  name: catalogkubedbcom-milvusversion-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
