chart:
  name: autoscalingkubedbcom-hanadbautoscaler-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a HanaDBAutoscaler Editor
  description: HanaDBAutoscaler Editor
  name: HanaDBAutoscaler Editor by AppsCode
  shortName: HanaDBAutoscaler Editor
  url: https://appscode.com
release:
  name: autoscalingkubedbcom-hanadbautoscaler-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
