chart:
  name: catalogappscodecom-qdrantbinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a QdrantBinding Editor
  description: QdrantBinding Editor
  name: QdrantBinding Editor by AppsCode
  shortName: QdrantBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-qdrantbinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
