form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      cluster:
        enabled: warning
        rules:
          galeraReplicationLatencyTooLong:
            duration: 5m
            enabled: true
            severity: warning
            val: 0.1
      database:
        enabled: warning
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          mysqlHighIncomingBytes:
            duration: 0m
            enabled: true
            severity: critical
            val: 1.048576e+06
          mysqlHighOutgoingBytes:
            duration: 0m
            enabled: true
            severity: critical
            val: 1.048576e+06
          mysqlHighQPS:
            duration: 0m
            enabled: true
            severity: critical
            val: 1000
          mysqlHighThreadsRunning:
            duration: 2m
            enabled: true
            severity: warning
            val: 60
          mysqlInnoDBLogWaits:
            duration: 0m
            enabled: true
            severity: warning
            val: 10
          mysqlInstanceDown:
            duration: 0m
            enabled: true
            severity: critical
          mysqlRestarted:
            duration: 0m
            enabled: true
            severity: warning
            val: 60
          mysqlServiceDown:
            duration: 0m
            enabled: true
            severity: critical
          mysqlSlowQueries:
            duration: 2m
            enabled: true
            severity: warning
          mysqlTooManyConnections:
            duration: 2m
            enabled: true
            severity: warning
            val: 80
          mysqlTooManyOpenFiles:
            duration: 2m
            enabled: true
            severity: warning
            val: 80
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
      schemaManager:
        enabled: warning
        rules:
          schemaExpired:
            duration: 0m
            enabled: true
            severity: warning
          schemaFailed:
            duration: 0m
            enabled: true
            severity: warning
          schemaInProgressForTooLong:
            duration: 30m
            enabled: true
            severity: warning
          schemaPendingForTooLong:
            duration: 30m
            enabled: true
            severity: warning
          schemaTerminatingForTooLong:
            duration: 30m
            enabled: true
            severity: warning
      stash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1
    name: perconaxtradbs
    kind: PerconaXtraDB
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComPerconaXtraDBAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: PerconaXtraDBAutoscaler
    metadata:
      name: perconaxtradb
      namespace: demo
  catalogAppscodeComPerconaXtraDBBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: PerconaXtraDBBinding
    metadata:
      name: perconaxtradb
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: perconaxtradb-ca
      namespace: demo
  gitopsKubedbComPerconaXtraDB: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: PerconaXtraDB
    metadata:
      name: perconaxtradb
      namespace: sdb
  kubedbComPerconaXtraDB: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: PerconaXtraDB
    metadata:
      name: perconaxtradb
      namespace: sdb
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: perconaxtradb
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: perconaxtradb-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: perconaxtradb-config
      namespace: demo
