step:
- elements:
  - individualDisability: disableFeatures
    init:
      type: func
      value: getEnabledFeatures
    label: ""
    loader: fetchFeatureSetOptions
    schema: temp/properties/enabledFeatures
    type: checkbox
    watcher:
      func: onEnabledFeaturesChange
      paths:
      - temp/properties/enabledFeatures
  - customClass: mt-24
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    type: info
    watcher:
      func: checkIsResourceLoaded
      paths:
      - temp/properties/isResourceLoaded
  id: opscenter-storage
  loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
type: multi-step-form
