chart:
  name: catalogappscodecom-neo4jbinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a Neo4jBinding Editor
  description: Neo4jBinding Editor
  name: Neo4jBinding Editor by AppsCode
  shortName: Neo4jBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-neo4jbinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
