chart:
  name: autoscalingkubedbcom-db2autoscaler-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DB2Autoscaler Editor
  description: DB2Autoscaler Editor
  name: DB2Autoscaler Editor by AppsCode
  shortName: DB2Autoscaler Editor
  url: https://appscode.com
release:
  name: autoscalingkubedbcom-db2autoscaler-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
