chart:
  name: catalogkubedbcom-qdrantversion-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a QdrantVersion Editor
  description: QdrantVersion Editor
  name: QdrantVersion Editor by AppsCode
  shortName: QdrantVersion Editor
  url: https://appscode.com
release:
  name: catalogkubedbcom-qdrantversion-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
