metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: weaviates
    kind: Weaviate
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComWeaviateAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: WeaviateAutoscaler
    metadata:
      name: weaviate
      namespace: demo
  kubedbComWeaviate: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: Weaviate
    metadata:
      name: weaviate
      namespace: default
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: weaviate-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: weaviate-config
      namespace: demo
