{{- if .Values.spec.configuration }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubedbcom-mariadb-editor-options.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedbcom-mariadb-editor-options.labels" . | nindent 4 }}
data:
  md-config.cnf: {{ .Values.spec.configuration | b64enc | quote }}
{{- end }}
{{- if and (eq .Values.spec.mode "MariaDBReplication") .Values.spec.maxscale.configuration }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubedbcom-mariadb-editor-options.fullname" . }}-maxscale-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedbcom-mariadb-editor-options.labels" . | nindent 4 }}
data:
  maxscale.cnf: {{ .Values.spec.maxscale.configuration | b64enc | quote }}
{{- end }}
