project:
  name: DocumentDB Editor UI Options
  shortName: DocumentDB Editor UI Options
  url: https://byte.builders
  description: DocumentDB Editor UI Options
  app: a DocumentDB Editor UI Options
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubedbcom-documentdb-editor-options
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: kubedbcom-documentdb-editor-options
  namespace: kube-system
