chart:
  name: catalogappscodecom-hanadbbinding-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a HanaDBBinding Editor
  description: HanaDBBinding Editor
  name: HanaDBBinding Editor by AppsCode
  shortName: HanaDBBinding Editor
  url: https://appscode.com
release:
  name: catalogappscodecom-hanadbbinding-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
