chart:
  name: courierkubedbcom-mysqlmigration-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a MySQLMigration Editor
  description: MySQLMigration Editor
  name: MySQLMigration Editor by AppsCode
  shortName: MySQLMigration Editor
  url: https://appscode.com
release:
  name: courierkubedbcom-mysqlmigration-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
