chart:
  name: courierkubedbcom-branch-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a Branch Editor
  description: Branch Editor
  name: Branch Editor by AppsCode
  shortName: Branch Editor
  url: https://appscode.com
release:
  name: courierkubedbcom-branch-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
