form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      cluster:
        enabled: warning
        rules:
          proxysqlClusterSyncFailure:
            duration: 5m
            enabled: true
            severity: warning
            val: 0.1
      database:
        enabled: warning
        rules:
          proxysqlHighIncomingBytes:
            duration: 0m
            enabled: true
            severity: critical
            val: 1.048576e+06
          proxysqlHighOutgoingBytes:
            duration: 0m
            enabled: true
            severity: critical
            val: 1.048576e+06
          proxysqlHighQPS:
            duration: 0m
            enabled: true
            severity: critical
            val: 1000
          proxysqlHighThreadsRunning:
            duration: 2m
            enabled: true
            severity: warning
            val: 60
          proxysqlInstanceDown:
            duration: 0m
            enabled: true
            severity: critical
          proxysqlRestarted:
            duration: 0m
            enabled: true
            severity: warning
            val: 60
          proxysqlServiceDown:
            duration: 0m
            enabled: true
            severity: critical
          proxysqlSlowQueries:
            duration: 2m
            enabled: true
            severity: warning
          proxysqlTooManyConnections:
            duration: 2m
            enabled: true
            severity: warning
            val: 80
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1
    name: proxysqls
    kind: ProxySQL
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComProxySQLAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: ProxySQLAutoscaler
    metadata:
      name: proxysql
      namespace: demo
  catalogAppscodeComProxySQLBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: ProxySQLBinding
    metadata:
      name: proxysql
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: proxysql-ca
      namespace: demo
  gitopsKubedbComProxySQL: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: ProxySQL
    metadata:
      name: proxysql
      namespace: demo
  kubedbComProxySQL: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: ProxySQL
    metadata:
      name: proxysql
      namespace: demo
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: proxysql
      namespace: demo
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: proxysql-auth
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: proxysql-config
      namespace: demo
