chart:
  name: autoscalingkubedbcom-weaviateautoscaler-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a WeaviateAutoscaler Editor
  description: WeaviateAutoscaler Editor
  name: WeaviateAutoscaler Editor by AppsCode
  shortName: WeaviateAutoscaler Editor
  url: https://appscode.com
release:
  name: autoscalingkubedbcom-weaviateautoscaler-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
