metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_appscode_otel_stack: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: appscode-otel-stack
      name: appscode-otel-stack
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_grafana_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: grafana-operator
      name: grafana-operator
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_inbox_agent: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: inbox-agent
      name: inbox-agent
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_inbox_server: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: inbox-server
      name: inbox-server
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_inbox_ui: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: inbox-ui
      name: inbox-ui
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kube_grafana_dashboards: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kube-grafana-dashboards
      name: kube-grafana-dashboards
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_kube_prometheus_stack: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: kube-prometheus-stack
      name: kube-prometheus-stack
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_metrics_server: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: metrics-server
      name: metrics-server
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_monitoring_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: monitoring-operator
      name: monitoring-operator
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_panopticon: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: panopticon
      name: panopticon
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_prom_label_proxy: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: prom-label-proxy
      name: prom-label-proxy
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_prometheus_adapter: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: prometheus-adapter
      name: prometheus-adapter
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_tenant_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: tenant-operator
      name: tenant-operator
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_thanos_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: thanos-operator
      name: thanos-operator
      namespace: kubeops
