form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      database:
        enabled: critical
        rules:
          diskAlmostFull:
            duration: 1m
            enabled: true
            severity: critical
            val: 95
          diskUsageHigh:
            duration: 1m
            enabled: true
            severity: warning
            val: 80
          elasticsearchClusterRed:
            duration: 0m
            enabled: true
            severity: critical
          elasticsearchClusterYellow:
            duration: 0m
            enabled: true
            severity: warning
          elasticsearchDiskOutOfSpace:
            duration: 0m
            enabled: true
            severity: critical
            val: 90
          elasticsearchDiskSpaceLow:
            duration: 2m
            enabled: true
            severity: warning
            val: 80
          elasticsearchHealthyDataNodes:
            duration: 0m
            enabled: true
            severity: critical
            val: 3
          elasticsearchHealthyNodes:
            duration: 0m
            enabled: true
            severity: critical
            val: 3
          elasticsearchHeapUsageTooHigh:
            duration: 2m
            enabled: true
            severity: critical
            val: 90
          elasticsearchHeapUsageWarning:
            duration: 2m
            enabled: true
            severity: warning
            val: 80
          elasticsearchInitializingShards:
            duration: 0m
            enabled: true
            severity: info
          elasticsearchNoNewDocuments10m:
            duration: 0m
            enabled: false
            severity: info
          elasticsearchPendingTasks:
            duration: 15m
            enabled: true
            severity: warning
          elasticsearchRelocatingShards:
            duration: 0m
            enabled: true
            severity: info
          elasticsearchUnassignedShards:
            duration: 0m
            enabled: true
            severity: critical
      kubeStash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      provisioner:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 1m
            enabled: true
            severity: critical
      stash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
    labels:
      release: kube-prometheus-stack
metadata:
  resource:
    group: kubedb.com
    version: v1
    name: elasticsearches
    kind: Elasticsearch
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  autoscalingKubedbComElasticsearchAutoscaler: # +doc-gen:break
    apiVersion: autoscaling.kubedb.com/v1alpha1
    kind: ElasticsearchAutoscaler
    metadata:
      name: elasticsearch
      namespace: demo
  catalogAppscodeComElasticsearchBinding: # +doc-gen:break
    apiVersion: catalog.appscode.com/v1alpha1
    kind: ElasticsearchBinding
    metadata:
      name: elasticsearch
      namespace: demo
  certManagerIoIssuer_ca: # +doc-gen:break
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: elasticsearch-ca
      namespace: demo
  coreKubestashComBackupBlueprint: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupBlueprint
    metadata:
      name: elasticsearch
      namespace: demo
  coreKubestashComBackupConfiguration: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
    metadata:
      name: elasticsearch
      namespace: demo
  coreKubestashComRestoreSession: # +doc-gen:break
    apiVersion: core.kubestash.com/v1alpha1
    kind: RestoreSession
    metadata:
      name: elasticsearch
      namespace: demo
  gitopsKubedbComElasticsearch: # +doc-gen:break
    apiVersion: gitops.kubedb.com/v1alpha1
    kind: Elasticsearch
    metadata:
      name: elasticsearch
      namespace: demo
  kubedbComElasticsearch: # +doc-gen:break
    apiVersion: kubedb.com/v1
    kind: Elasticsearch
    metadata:
      name: elasticsearch
      namespace: demo
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: elasticsearch
      namespace: demo
  secret_admin_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-admin-cred
      namespace: demo
  secret_elastic_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-elastic-cred
      namespace: demo
  secret_encryption_secret: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-encryption-secret
      namespace: demo
  secret_init_repo_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-init-repo-cred
      namespace: demo
  secret_kibanaro_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-kibanaro-cred
      namespace: demo
  secret_kibanaserver_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-kibanaserver-cred
      namespace: demo
  secret_logstash_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-logstash-cred
      namespace: demo
  secret_metrics_exporter_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-metrics-exporter-cred
      namespace: demo
  secret_readall_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-readall-cred
      namespace: demo
  secret_repo_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-repo-cred
      namespace: demo
  secret_secure_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-secure-config
      namespace: demo
  secret_snapshotrestore_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-snapshotrestore-cred
      namespace: demo
  secret_user_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: elasticsearch-user-config
      namespace: demo
  stashAppscodeComBackupConfiguration: # +doc-gen:break
    apiVersion: stash.appscode.com/v1beta1
    kind: BackupConfiguration
    metadata:
      name: elasticsearch
      namespace: demo
  stashAppscodeComRepository_init_repo: # +doc-gen:break
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: elasticsearch-init-repo
      namespace: demo
  stashAppscodeComRepository_repo: # +doc-gen:break
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: elasticsearch-repo
      namespace: demo
  stashAppscodeComRestoreSession_init: # +doc-gen:break
    apiVersion: stash.appscode.com/v1beta1
    kind: RestoreSession
    metadata:
      name: elasticsearch-init
      namespace: demo
