metadata:
  resource:
    group: ui.k8s.appscode.com
    version: v1alpha1
    name: featuresets
    kind: FeatureSet
    scope: Cluster
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  helmToolkitFluxcdIoHelmRelease_aws_credential_manager: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: aws-credential-manager
      name: aws-credential-manager
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_aws_ebs_csi_driver: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: aws-ebs-csi-driver
      name: aws-ebs-csi-driver
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_aws_load_balancer_controller: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: aws-load-balancer-controller
      name: aws-load-balancer-controller
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_capa_vpc_peering_operator: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: capa-vpc-peering-operator
      name: capa-vpc-peering-operator
      namespace: kubeops
  helmToolkitFluxcdIoHelmRelease_cluster_autoscaler: # +doc-gen:break
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      labels:
        app.kubernetes.io/component: cluster-autoscaler
      name: cluster-autoscaler
      namespace: kubeops
