form:
  alert:
    additionalRuleLabels: {}
    annotations: {}
    enabled: warning
    groups:
      operator:
        enabled: warning
        rules:
          appPhaseCritical:
            duration: 15m
            enabled: true
            severity: warning
          appPhaseNotReady:
            duration: 5m
            enabled: true
            severity: critical
      opsManager:
        enabled: warning
        rules:
          opsRequestFailed:
            duration: 0m
            enabled: true
            severity: critical
          opsRequestOnProgress:
            duration: 0m
            enabled: true
            severity: info
          opsRequestStatusProgressingToLong:
            duration: 30m
            enabled: true
            severity: critical
      stash:
        enabled: warning
        rules:
          backupSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          backupSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
          noBackupSessionForTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 18000
          repositoryCorrupted:
            duration: 5m
            enabled: true
            severity: critical
          repositoryStorageRunningLow:
            duration: 5m
            enabled: true
            severity: warning
            val: 1.073741824e+10
          restoreSessionFailed:
            duration: 0m
            enabled: true
            severity: critical
          restoreSessionPeriodTooLong:
            duration: 0m
            enabled: true
            severity: warning
            val: 1800
      vault:
        enabled: warning
        rules:
          vaultAutoPilotNodeUnhealthy:
            duration: 1m
            enabled: true
            severity: critical
          vaultDown:
            duration: 0m
            enabled: true
            severity: critical
          vaultLeadershipLoss:
            duration: 1m
            enabled: true
            severity: critical
            val: 5
          vaultLeadershipSetupFailures:
            duration: 1m
            enabled: true
            severity: critical
            val: 5
          vaultLeadershipStepsDowns:
            duration: 1m
            enabled: true
            severity: critical
            val: 5
          vaultRequestFailures:
            duration: 15m
            enabled: true
            severity: critical
          vaultResponseFailures:
            duration: 15m
            enabled: true
            severity: critical
          vaultSealed:
            duration: 0m
            enabled: true
            severity: critical
          vaultTooManyInfinityTokens:
            duration: 5m
            enabled: true
            severity: warning
            val: 3
    labels:
      release: prometheus
  capi:
    clusterName: ""
    dedicated: false
    namespace: ""
    nodes: 1
    provider: ""
    sku: ""
    zones: []
metadata:
  resource:
    group: kubevault.com
    version: v1alpha1
    name: vaultservers
    kind: VaultServer
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  kubevaultComVaultServer: # +doc-gen:break
    apiVersion: kubevault.com/v1alpha2
    kind: VaultServer
    metadata:
      name: vault
      namespace: default
  monitoringCoreosComServiceMonitor: # +doc-gen:break
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: vault
      namespace: default
  secret_backend_creds: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: vault-backend-creds
      namespace: demo
  secret_backend_tls: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: vault-backend-tls
      namespace: demo
  secret_config: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: vault-config
      namespace: demo
  secret_repo_cred: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: vault-repo-cred
      namespace: default
  secret_unsealer_creds: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: vault-unsealer-creds
      namespace: demo
  stashAppscodeComBackupConfiguration: # +doc-gen:break
    apiVersion: stash.appscode.com/v1beta1
    kind: BackupConfiguration
    metadata:
      name: vault
      namespace: default
  stashAppscodeComRepository_repo: # +doc-gen:break
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
    metadata:
      name: vault-repo
      namespace: default
