step:
- loader: setReleaseNameAndNamespaceAndInitializeValues
  type: single-step-form
  id: opscenter-datastore
  elements:
  - type: checkbox
    schema: temp/properties/enabledFeatures
    label: ''
    loader: fetchFeatureSetOptions
    init:
      type: func
      value: getEnabledFeatures
    watcher:
      func: onEnabledFeaturesChange
      paths:
        - temp/properties/enabledFeatures
  - type: info
    label: 'Note: Enabling a feature auto enables any prerequisite features'
    customClass: mt-24
    watcher:
      func: checkIsResourceLoaded
      paths:
        - temp/properties/isResourceLoaded
  - type: block-layout
    if:
      name: checkSpokeComponent
      type: function
    elements:
    - type: label-element
      label: Hub Information
    - type: select
      label: Select Hub
      loader: getHubList
      schema: temp/properties/hubName
      validation:
        type: required
    - type: input
      loader:
        name: getHubInfo|apiServer
        watchPaths:
          - temp/properties/hubName
      label: Api Server
      disable: true
      if:
        name: isHubSelected
        type: function
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_cluster_manager_spoke/properties/spec/properties/values/properties/hub/properties/apiServer
      validation:
        type: required
    - type: input
      loader:
        name: getHubInfo|apiServer
        watchPaths:
          - temp/properties/hubName
      label: Token
      disable: true
      if:
        name: isHubSelected
        type: function
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_cluster_manager_spoke/properties/spec/properties/values/properties/hub/properties/token
      validation:
        type: required
    - type: label-element
      label: Spoke Information
    - type: input
      label: Cluster Name
      description: 'Cluster Name Must not Be Same As any Managed Cluster '
      init:
        type: func
        value: getClusterName
      schema: schema/properties/resources/properties/helmToolkitFluxcdIoHelmRelease_cluster_manager_spoke/properties/spec/properties/values/properties/clusterMetadata/properties/name
      validation:
        type: required
type: multi-step-form
