chart:
  name: operatork8sappscodecom-shardconfiguration-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a ShardConfiguration Editor
  description: ShardConfiguration Editor
  name: ShardConfiguration Editor by AppsCode
  shortName: ShardConfiguration Editor
  url: https://appscode.com
release:
  name: operatork8sappscodecom-shardconfiguration-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
