chart:
  name: autoscalingkubedbcom-documentdbautoscaler-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DocumentDBAutoscaler Editor
  description: DocumentDBAutoscaler Editor
  name: DocumentDBAutoscaler Editor by AppsCode
  shortName: DocumentDBAutoscaler Editor
  url: https://appscode.com
release:
  name: autoscalingkubedbcom-documentdbautoscaler-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
