chart:
  name: opskubedbcom-milvusopsrequest-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a MilvusOpsRequest Editor
  description: MilvusOpsRequest Editor
  name: MilvusOpsRequest Editor by AppsCode
  shortName: MilvusOpsRequest Editor
  url: https://appscode.com
release:
  name: opskubedbcom-milvusopsrequest-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
