chart:
  name: kubedbcom-db2-editor
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
project:
  app: a DB2 Editor
  description: DB2 Editor
  name: DB2 Editor by AppsCode
  shortName: DB2 Editor
  url: https://appscode.com
release:
  name: kubedbcom-db2-editor
  namespace: default
repository:
  name: appscode
  url: https://charts.appscode.com/stable/
