metadata:
  resource:
    group: kubedb.com
    version: v1alpha2
    name: db2s
    kind: DB2
    scope: Namespaced
  release:
    name: RELEASE-NAME
    namespace: default
resources:
  kubedbComDB2: # +doc-gen:break
    apiVersion: kubedb.com/v1alpha2
    kind: DB2
    metadata:
      name: db2
      namespace: default
  secret_auth: # +doc-gen:break
    apiVersion: v1
    kind: Secret
    metadata:
      name: db2-auth
      namespace: demo
